export interface GlobalStockItem {
  ticker: string;
  name: string;
  type: 'Stock' | 'ETF' | 'Index';
  category: 'stocks' | 'etfs' | 'indices';
  region: 'US' | 'Canada' | 'Europe' | 'Asia' | 'Latin America' | 'Emerging Markets' | 'Global';
  country: string;
  exchange: string;
  currency: string;
  sector: string;
  industry?: string;
  current_price: number;
  day_change: number;
  day_change_pct: number;
  volume_24h: string;
  market_cap: string;
  pe_ratio: number | null;
  high_52w: number;
  low_52w: number;
  beta: number;
  eps: number | null;
  description: string;
  ai_summary: string;
  ai_sentiment: 'Bullish' | 'Neutral' | 'Bearish';
  color: string;
}

export const GLOBAL_STOCKS_UNIVERSE: GlobalStockItem[] = [
  // =========================================================================
  // 1. UNITED STATES EQUITIES (Mega-Cap & Large-Cap Blue Chips)
  // =========================================================================
  {
    ticker: 'AAPL',
    name: 'Apple Inc.',
    type: 'Stock',
    category: 'stocks',
    region: 'US',
    country: 'United States',
    exchange: 'NASDAQ',
    currency: 'USD',
    sector: 'Technology Hardware',
    industry: 'Consumer Electronics',
    current_price: 224.23,
    day_change: 3.12,
    day_change_pct: 1.41,
    volume_24h: '48.2M',
    market_cap: '$3.42T',
    pe_ratio: 34.1,
    high_52w: 237.23,
    low_52w: 164.08,
    beta: 1.12,
    eps: 6.57,
    description: 'Apple Inc. designs, manufactures, and markets smartphones, personal computers, tablets, wearables, and accessories, and sells a variety of related services.',
    ai_summary: 'Consistently strong ecosystem retention, expanding high-margin services revenue, and Apple Intelligence rollouts support resilient cash flows.',
    ai_sentiment: 'Bullish',
    color: '#000000',
  },
  {
    ticker: 'NVDA',
    name: 'NVIDIA Corporation',
    type: 'Stock',
    category: 'stocks',
    region: 'US',
    country: 'United States',
    exchange: 'NASDAQ',
    currency: 'USD',
    sector: 'Semiconductors',
    industry: 'Semiconductors',
    current_price: 128.85,
    day_change: 5.40,
    day_change_pct: 4.37,
    volume_24h: '65.4M',
    market_cap: '$3.16T',
    pe_ratio: 58.2,
    high_52w: 140.76,
    low_52w: 40.85,
    beta: 1.68,
    eps: 2.21,
    description: 'NVIDIA Corporation provides graphics, computing, and networking solutions, pioneering the global GPU hardware and enterprise AI acceleration market.',
    ai_summary: 'Dominant global AI data center GPU market share exceeding 80%, robust gross margins, and expanding Blackwell architecture volume.',
    ai_sentiment: 'Bullish',
    color: '#76B900',
  },
  {
    ticker: 'MSFT',
    name: 'Microsoft Corporation',
    type: 'Stock',
    category: 'stocks',
    region: 'US',
    country: 'United States',
    exchange: 'NASDAQ',
    currency: 'USD',
    sector: 'Software & Cloud',
    industry: 'Infrastructure Software',
    current_price: 418.40,
    day_change: 2.15,
    day_change_pct: 0.52,
    volume_24h: '22.1M',
    market_cap: '$3.11T',
    pe_ratio: 36.4,
    high_52w: 468.35,
    low_52w: 309.45,
    beta: 0.95,
    eps: 11.50,
    description: 'Microsoft Corporation develops and supports software, services, devices, and enterprise cloud solutions including Azure, Microsoft 365, and AI integrations.',
    ai_summary: 'Hyper-growth in Azure cloud computing, Copilot AI enterprise adoption, and enterprise balance sheet stability drive sustained valuation support.',
    ai_sentiment: 'Bullish',
    color: '#00A4EF',
  },
  {
    ticker: 'AMZN',
    name: 'Amazon.com Inc.',
    type: 'Stock',
    category: 'stocks',
    region: 'US',
    country: 'United States',
    exchange: 'NASDAQ',
    currency: 'USD',
    sector: 'E-Commerce & Cloud',
    industry: 'Internet Retail',
    current_price: 177.50,
    day_change: -1.20,
    day_change_pct: -0.67,
    volume_24h: '38.6M',
    market_cap: '$1.85T',
    pe_ratio: 42.8,
    high_52w: 201.20,
    low_52w: 118.35,
    beta: 1.15,
    eps: 4.15,
    description: 'Amazon.com, Inc. focuses on retail sale of consumer products and subscriptions through online and physical stores, cloud services via AWS, and digital advertising.',
    ai_summary: 'AWS cloud margin expansion, rapid advertising segment monetization, and optimized logistics networks underpin continuous free cash flow expansion.',
    ai_sentiment: 'Bullish',
    color: '#FF9900',
  },
  {
    ticker: 'GOOGL',
    name: 'Alphabet Inc.',
    type: 'Stock',
    category: 'stocks',
    region: 'US',
    country: 'United States',
    exchange: 'NASDAQ',
    currency: 'USD',
    sector: 'Interactive Media',
    industry: 'Internet Content & Information',
    current_price: 165.20,
    day_change: 0.85,
    day_change_pct: 0.52,
    volume_24h: '24.8M',
    market_cap: '$2.04T',
    pe_ratio: 23.5,
    high_52w: 191.75,
    low_52w: 120.21,
    beta: 1.05,
    eps: 7.03,
    description: 'Alphabet Inc. offers products and platforms globally, operating through Google Services, Google Cloud, and Other Bets.',
    ai_summary: 'Search advertising moat remains intact while Google Cloud profitability accelerates alongside Gemini AI enterprise integration.',
    ai_sentiment: 'Bullish',
    color: '#4285F4',
  },
  {
    ticker: 'META',
    name: 'Meta Platforms Inc.',
    type: 'Stock',
    category: 'stocks',
    region: 'US',
    country: 'United States',
    exchange: 'NASDAQ',
    currency: 'USD',
    sector: 'Interactive Media',
    industry: 'Internet Content & Information',
    current_price: 512.60,
    day_change: 8.40,
    day_change_pct: 1.67,
    volume_24h: '14.2M',
    market_cap: '$1.30T',
    pe_ratio: 26.8,
    high_52w: 544.23,
    low_52w: 279.40,
    beta: 1.22,
    eps: 19.12,
    description: 'Meta Platforms, Inc. engages in the development of products that enable people to connect through mobile devices, personal computers, VR, and in-app feeds.',
    ai_summary: 'World-class monetization of Reels, open-source Llama AI advancements, and strong digital ad pricing deliver top-tier operating margins.',
    ai_sentiment: 'Bullish',
    color: '#0668E1',
  },
  {
    ticker: 'TSLA',
    name: 'Tesla Inc.',
    type: 'Stock',
    category: 'stocks',
    region: 'US',
    country: 'United States',
    exchange: 'NASDAQ',
    currency: 'USD',
    sector: 'Automotive & Energy',
    industry: 'Auto Manufacturers',
    current_price: 218.40,
    day_change: -4.80,
    day_change_pct: -2.15,
    volume_24h: '78.5M',
    market_cap: '$696B',
    pe_ratio: 62.4,
    high_52w: 271.00,
    low_52w: 138.80,
    beta: 2.35,
    eps: 3.50,
    description: 'Tesla, Inc. designs, develops, manufactures, sells, and leases fully electric vehicles, energy storage systems, solar panels, and Full Self-Driving software.',
    ai_summary: 'Autonomous driving software progress (FSD) and Megapack energy storage revenue mitigate short-term EV gross margin pressure.',
    ai_sentiment: 'Neutral',
    color: '#CC0000',
  },
  {
    ticker: 'AVGO',
    name: 'Broadcom Inc.',
    type: 'Stock',
    category: 'stocks',
    region: 'US',
    country: 'United States',
    exchange: 'NASDAQ',
    currency: 'USD',
    sector: 'Semiconductors',
    industry: 'Semiconductors',
    current_price: 158.40,
    day_change: 2.90,
    day_change_pct: 1.86,
    volume_24h: '24.1M',
    market_cap: '$738B',
    pe_ratio: 38.5,
    high_52w: 185.16,
    low_52w: 80.82,
    beta: 1.25,
    eps: 4.11,
    description: 'Broadcom Inc. designs, develops, and supplies semiconductor devices and enterprise software infrastructure.',
    ai_summary: 'Leading custom AI ASIC silicon solutions for hyper-scalers and VMware recurring enterprise software revenue synergies.',
    ai_sentiment: 'Bullish',
    color: '#CC092F',
  },
  {
    ticker: 'AMD',
    name: 'Advanced Micro Devices',
    type: 'Stock',
    category: 'stocks',
    region: 'US',
    country: 'United States',
    exchange: 'NASDAQ',
    currency: 'USD',
    sector: 'Semiconductors',
    industry: 'Semiconductors',
    current_price: 148.60,
    day_change: 3.20,
    day_change_pct: 2.20,
    volume_24h: '52.1M',
    market_cap: '$240B',
    pe_ratio: 110.2,
    high_52w: 227.30,
    low_52w: 94.04,
    beta: 1.70,
    eps: 1.35,
    description: 'Advanced Micro Devices, Inc. operates as a semiconductor company worldwide, offering x86 microprocessors, GPUs, and data center accelerators.',
    ai_summary: 'MI300 AI accelerator revenue ramps quickly alongside EPYC server market share expansion in enterprise cloud.',
    ai_sentiment: 'Bullish',
    color: '#ED1C24',
  },
  {
    ticker: 'NFLX',
    name: 'Netflix Inc.',
    type: 'Stock',
    category: 'stocks',
    region: 'US',
    country: 'United States',
    exchange: 'NASDAQ',
    currency: 'USD',
    sector: 'Entertainment',
    industry: 'Entertainment',
    current_price: 685.20,
    day_change: 6.80,
    day_change_pct: 1.00,
    volume_24h: '3.4M',
    market_cap: '$294B',
    pe_ratio: 42.1,
    high_52w: 711.33,
    low_52w: 344.73,
    beta: 1.28,
    eps: 16.27,
    description: 'Netflix, Inc. provides entertainment services, offering TV series, documentaries, feature films, and games across various genres and languages.',
    ai_summary: 'Paid sharing initiatives, ad-supported tier subscriber momentum, and live sports broadcasting expand operating margin.',
    ai_sentiment: 'Bullish',
    color: '#E50914',
  },
  {
    ticker: 'ORCL',
    name: 'Oracle Corporation',
    type: 'Stock',
    category: 'stocks',
    region: 'US',
    country: 'United States',
    exchange: 'NYSE',
    currency: 'USD',
    sector: 'Software & Cloud',
    industry: 'Software - Infrastructure',
    current_price: 138.90,
    day_change: 1.80,
    day_change_pct: 1.31,
    volume_24h: '11.2M',
    market_cap: '$382B',
    pe_ratio: 35.8,
    high_52w: 146.59,
    low_52w: 99.26,
    beta: 1.04,
    eps: 3.88,
    description: 'Oracle Corporation offers products and services that address enterprise information technology environments worldwide.',
    ai_summary: 'OCI Gen 2 Cloud infrastructure demand for AI model training drives massive backlog expansion.',
    ai_sentiment: 'Bullish',
    color: '#F80000',
  },
  {
    ticker: 'CRM',
    name: 'Salesforce Inc.',
    type: 'Stock',
    category: 'stocks',
    region: 'US',
    country: 'United States',
    exchange: 'NYSE',
    currency: 'USD',
    sector: 'Software & Cloud',
    industry: 'Software - Application',
    current_price: 258.40,
    day_change: 2.10,
    day_change_pct: 0.82,
    volume_24h: '6.8M',
    market_cap: '$249B',
    pe_ratio: 45.2,
    high_52w: 318.71,
    low_52w: 193.68,
    beta: 1.18,
    eps: 5.72,
    description: 'Salesforce, Inc. provides Customer Relationship Management technology that brings companies and customers together globally.',
    ai_summary: 'Agentforce autonomous AI agents and Data Cloud adoption drive enterprise software monetization.',
    ai_sentiment: 'Bullish',
    color: '#00A1E0',
  },
  {
    ticker: 'ADBE',
    name: 'Adobe Inc.',
    type: 'Stock',
    category: 'stocks',
    region: 'US',
    country: 'United States',
    exchange: 'NASDAQ',
    currency: 'USD',
    sector: 'Software & Cloud',
    industry: 'Software - Infrastructure',
    current_price: 545.10,
    day_change: 4.30,
    day_change_pct: 0.80,
    volume_24h: '3.1M',
    market_cap: '$241B',
    pe_ratio: 48.6,
    high_52w: 638.25,
    low_52w: 433.97,
    beta: 1.30,
    eps: 11.21,
    description: 'Adobe Inc. operates as a diversified software company providing creative, marketing, and document management solutions.',
    ai_summary: 'Firefly generative AI embedded across Creative Cloud and Document Cloud enhances professional workflows.',
    ai_sentiment: 'Bullish',
    color: '#FF0000',
  },
  {
    ticker: 'INTC',
    name: 'Intel Corporation',
    type: 'Stock',
    category: 'stocks',
    region: 'US',
    country: 'United States',
    exchange: 'NASDAQ',
    currency: 'USD',
    sector: 'Semiconductors',
    industry: 'Semiconductors',
    current_price: 21.50,
    day_change: -0.45,
    day_change_pct: -2.05,
    volume_24h: '68.2M',
    market_cap: '$92B',
    pe_ratio: null,
    high_52w: 51.28,
    low_52w: 18.84,
    beta: 1.10,
    eps: -0.38,
    description: 'Intel Corporation designs, develops, manufactures, markets, and sells computing and related products worldwide.',
    ai_summary: 'Turnaround plan focused on foundry manufacturing (Intel 18A) and cost reduction restructuring.',
    ai_sentiment: 'Neutral',
    color: '#0071C5',
  },
  {
    ticker: 'QCOM',
    name: 'Qualcomm Inc.',
    type: 'Stock',
    category: 'stocks',
    region: 'US',
    country: 'United States',
    exchange: 'NASDAQ',
    currency: 'USD',
    sector: 'Semiconductors',
    industry: 'Semiconductors',
    current_price: 168.30,
    day_change: 2.15,
    day_change_pct: 1.29,
    volume_24h: '9.4M',
    market_cap: '$188B',
    pe_ratio: 21.4,
    high_52w: 230.63,
    low_52w: 104.33,
    beta: 1.26,
    eps: 7.86,
    description: 'QUALCOMM Incorporated engages in the development and commercialization of foundational technologies for the wireless industry.',
    ai_summary: 'Snapdragon X Elite PC chips and automotive digital chassis expansion diversify beyond smartphones.',
    ai_sentiment: 'Bullish',
    color: '#3253DC',
  },
  {
    ticker: 'MU',
    name: 'Micron Technology Inc.',
    type: 'Stock',
    category: 'stocks',
    region: 'US',
    country: 'United States',
    exchange: 'NASDAQ',
    currency: 'USD',
    sector: 'Semiconductors',
    industry: 'Semiconductors',
    current_price: 98.40,
    day_change: 3.10,
    day_change_pct: 3.25,
    volume_24h: '28.4M',
    market_cap: '$109B',
    pe_ratio: 32.1,
    high_52w: 157.50,
    low_52w: 65.40,
    beta: 1.45,
    eps: 3.06,
    description: 'Micron Technology, Inc. designs, develops, manufactures, and sells memory and storage products worldwide.',
    ai_summary: 'High Bandwidth Memory (HBM3E) demand for AI GPU accelerators sold out through next calendar year.',
    ai_sentiment: 'Bullish',
    color: '#005596',
  },
  {
    ticker: 'CSCO',
    name: 'Cisco Systems Inc.',
    type: 'Stock',
    category: 'stocks',
    region: 'US',
    country: 'United States',
    exchange: 'NASDAQ',
    currency: 'USD',
    sector: 'Networking Hardware',
    industry: 'Communication Equipment',
    current_price: 49.80,
    day_change: 0.35,
    day_change_pct: 0.71,
    volume_24h: '18.2M',
    market_cap: '$199B',
    pe_ratio: 19.2,
    high_52w: 58.19,
    low_52w: 44.50,
    beta: 0.85,
    eps: 2.59,
    description: 'Cisco Systems, Inc. designs and sells a broad range of technologies that power the Internet, enterprise networking, and cybersecurity.',
    ai_summary: 'Splunk integration accelerates recurring cybersecurity and observability software revenues.',
    ai_sentiment: 'Neutral',
    color: '#049FD9',
  },
  {
    ticker: 'IBM',
    name: 'International Business Machines',
    type: 'Stock',
    category: 'stocks',
    region: 'US',
    country: 'United States',
    exchange: 'NYSE',
    currency: 'USD',
    sector: 'IT Services & Cloud',
    industry: 'Information Technology Services',
    current_price: 194.20,
    day_change: 1.40,
    day_change_pct: 0.73,
    volume_24h: '4.2M',
    market_cap: '$178B',
    pe_ratio: 22.4,
    high_52w: 199.18,
    low_52w: 137.34,
    beta: 0.72,
    eps: 8.67,
    description: 'International Business Machines Corporation provides hybrid cloud infrastructure, software, and consulting services worldwide.',
    ai_summary: 'watsonx generative AI platform and Red Hat hybrid cloud expand enterprise consulting pipeline.',
    ai_sentiment: 'Bullish',
    color: '#0530AD',
  },

  // US Financials
  {
    ticker: 'JPM',
    name: 'JPMorgan Chase & Co.',
    type: 'Stock',
    category: 'stocks',
    region: 'US',
    country: 'United States',
    exchange: 'NYSE',
    currency: 'USD',
    sector: 'Financial Services',
    industry: 'Banks - Diversified',
    current_price: 214.80,
    day_change: 1.90,
    day_change_pct: 0.89,
    volume_24h: '8.9M',
    market_cap: '$612B',
    pe_ratio: 12.1,
    high_52w: 225.48,
    low_52w: 140.40,
    beta: 1.08,
    eps: 17.75,
    description: 'JPMorgan Chase & Co. operates as a financial services company worldwide, providing investment banking, asset management, and commercial banking.',
    ai_summary: 'Fortress balance sheet, sector-leading Net Interest Income, and dominant investment banking fee leadership.',
    ai_sentiment: 'Bullish',
    color: '#117ACA',
  },
  {
    ticker: 'BAC',
    name: 'Bank of America Corp.',
    type: 'Stock',
    category: 'stocks',
    region: 'US',
    country: 'United States',
    exchange: 'NYSE',
    currency: 'USD',
    sector: 'Financial Services',
    industry: 'Banks - Diversified',
    current_price: 39.40,
    day_change: 0.45,
    day_change_pct: 1.15,
    volume_24h: '36.5M',
    market_cap: '$308B',
    pe_ratio: 13.5,
    high_52w: 44.44,
    low_52w: 24.96,
    beta: 1.32,
    eps: 2.92,
    description: 'Bank of America Corporation provides banking and financial products and services for individual consumers, small and middle-market businesses.',
    ai_summary: 'Consumer deposit stability and wealth management asset inflows support steady net interest recovery.',
    ai_sentiment: 'Bullish',
    color: '#E31837',
  },
  {
    ticker: 'GS',
    name: 'The Goldman Sachs Group',
    type: 'Stock',
    category: 'stocks',
    region: 'US',
    country: 'United States',
    exchange: 'NYSE',
    currency: 'USD',
    sector: 'Financial Services',
    industry: 'Capital Markets',
    current_price: 495.20,
    day_change: 5.60,
    day_change_pct: 1.14,
    volume_24h: '2.1M',
    market_cap: '$162B',
    pe_ratio: 15.2,
    high_52w: 512.60,
    low_52w: 289.36,
    beta: 1.38,
    eps: 32.58,
    description: 'The Goldman Sachs Group, Inc. operates as an investment banking, securities, and investment management company worldwide.',
    ai_summary: 'Global M&A resurgence and equity underwriting recovery boost advisory and trading revenues.',
    ai_sentiment: 'Bullish',
    color: '#21538A',
  },
  {
    ticker: 'MS',
    name: 'Morgan Stanley',
    type: 'Stock',
    category: 'stocks',
    region: 'US',
    country: 'United States',
    exchange: 'NYSE',
    currency: 'USD',
    sector: 'Financial Services',
    industry: 'Capital Markets',
    current_price: 98.60,
    day_change: 1.10,
    day_change_pct: 1.13,
    volume_24h: '5.8M',
    market_cap: '$159B',
    pe_ratio: 16.4,
    high_52w: 105.80,
    low_52w: 69.42,
    beta: 1.30,
    eps: 6.01,
    description: 'Morgan Stanley provides a wide range of investment banking, securities, wealth management, and investment management services.',
    ai_summary: 'Massive wealth management client asset base generates reliable recurring fee income.',
    ai_sentiment: 'Bullish',
    color: '#002B49',
  },
  {
    ticker: 'V',
    name: 'Visa Inc.',
    type: 'Stock',
    category: 'stocks',
    region: 'US',
    country: 'United States',
    exchange: 'NYSE',
    currency: 'USD',
    sector: 'Payment Processing',
    industry: 'Credit Services',
    current_price: 268.40,
    day_change: 1.20,
    day_change_pct: 0.45,
    volume_24h: '5.6M',
    market_cap: '$546B',
    pe_ratio: 28.5,
    high_52w: 290.96,
    low_52w: 227.78,
    beta: 0.94,
    eps: 9.42,
    description: 'Visa Inc. operates the world’s largest retail electronic payments network, connecting consumers, merchants, financial institutions, and government entities.',
    ai_summary: 'Global cross-border travel volume strength and robust operating margins above 65% provide defensive fintech growth.',
    ai_sentiment: 'Bullish',
    color: '#1A1F71',
  },
  {
    ticker: 'MA',
    name: 'Mastercard Inc.',
    type: 'Stock',
    category: 'stocks',
    region: 'US',
    country: 'United States',
    exchange: 'NYSE',
    currency: 'USD',
    sector: 'Payment Processing',
    industry: 'Credit Services',
    current_price: 472.50,
    day_change: 2.80,
    day_change_pct: 0.60,
    volume_24h: '2.8M',
    market_cap: '$438B',
    pe_ratio: 34.2,
    high_52w: 494.50,
    low_52w: 362.40,
    beta: 1.05,
    eps: 13.82,
    description: 'Mastercard Incorporated provides transaction processing and other payment-related products and services in the United States and internationally.',
    ai_summary: 'Value-added services growth including fraud prevention and cross-border digital payment expansion.',
    ai_sentiment: 'Bullish',
    color: '#EB001B',
  },

  // US Retail, Consumer & Entertainment
  {
    ticker: 'WMT',
    name: 'Walmart Inc.',
    type: 'Stock',
    category: 'stocks',
    region: 'US',
    country: 'United States',
    exchange: 'NYSE',
    currency: 'USD',
    sector: 'Consumer Staples',
    industry: 'Discount Stores',
    current_price: 74.25,
    day_change: 0.65,
    day_change_pct: 0.88,
    volume_24h: '19.4M',
    market_cap: '$598B',
    pe_ratio: 31.8,
    high_52w: 75.88,
    low_52w: 49.85,
    beta: 0.52,
    eps: 2.33,
    description: 'Walmart Inc. engages in retail and wholesale operations worldwide, offering an assortment of merchandise and services at everyday low prices.',
    ai_summary: 'Grocery market share gains across high-income demographics, rapid e-commerce delivery expansion, and advertising high-margin monetization.',
    ai_sentiment: 'Bullish',
    color: '#0071CE',
  },
  {
    ticker: 'COST',
    name: 'Costco Wholesale Corp.',
    type: 'Stock',
    category: 'stocks',
    region: 'US',
    country: 'United States',
    exchange: 'NASDAQ',
    currency: 'USD',
    sector: 'Consumer Staples',
    industry: 'Discount Stores',
    current_price: 885.20,
    day_change: 6.40,
    day_change_pct: 0.73,
    volume_24h: '1.8M',
    market_cap: '$392B',
    pe_ratio: 54.2,
    high_52w: 900.25,
    low_52w: 535.10,
    beta: 0.78,
    eps: 16.33,
    description: 'Costco Wholesale Corporation operates membership warehouses that offer branded and private-label products in a range of merchandise categories.',
    ai_summary: 'Industry-best 93%+ membership renewal rates and steady international store unit expansion.',
    ai_sentiment: 'Bullish',
    color: '#E31837',
  },
  {
    ticker: 'HD',
    name: 'The Home Depot Inc.',
    type: 'Stock',
    category: 'stocks',
    region: 'US',
    country: 'United States',
    exchange: 'NYSE',
    currency: 'USD',
    sector: 'Consumer Discretionary',
    industry: 'Home Improvement Retail',
    current_price: 365.40,
    day_change: 2.10,
    day_change_pct: 0.58,
    volume_24h: '3.9M',
    market_cap: '$362B',
    pe_ratio: 24.1,
    high_52w: 395.20,
    low_52w: 274.26,
    beta: 0.98,
    eps: 15.16,
    description: 'The Home Depot, Inc. operates as a home improvement retailer, offering building materials, home improvement products, lawn and garden products.',
    ai_summary: 'Pro customer expansion and housing turnover recovery positioning bolster long-term market share.',
    ai_sentiment: 'Neutral',
    color: '#F96302',
  },
  {
    ticker: 'MCD',
    name: "McDonald's Corporation",
    type: 'Stock',
    category: 'stocks',
    region: 'US',
    country: 'United States',
    exchange: 'NYSE',
    currency: 'USD',
    sector: 'Consumer Discretionary',
    industry: 'Restaurants',
    current_price: 288.90,
    day_change: 1.40,
    day_change_pct: 0.49,
    volume_24h: '2.8M',
    market_cap: '$208B',
    pe_ratio: 25.1,
    high_52w: 302.39,
    low_52w: 243.53,
    beta: 0.68,
    eps: 11.51,
    description: "McDonald's Corporation operates and franchises McDonald's restaurants in the United States and internationally.",
    ai_summary: 'Value menu initiatives and high-margin global real estate franchising royalty model.',
    ai_sentiment: 'Bullish',
    color: '#FFBC0D',
  },
  {
    ticker: 'KO',
    name: 'The Coca-Cola Company',
    type: 'Stock',
    category: 'stocks',
    region: 'US',
    country: 'United States',
    exchange: 'NYSE',
    currency: 'USD',
    sector: 'Consumer Staples',
    industry: 'Beverages - Non-Alcoholic',
    current_price: 68.40,
    day_change: 0.30,
    day_change_pct: 0.44,
    volume_24h: '12.4M',
    market_cap: '$294B',
    pe_ratio: 27.2,
    high_52w: 70.18,
    low_52w: 51.55,
    beta: 0.58,
    eps: 2.51,
    description: 'The Coca-Cola Company manufactures, markets, and sells various nonalcoholic beverages worldwide.',
    ai_summary: 'Pricing power across global beverage distribution networks and consistent 3%+ dividend yield.',
    ai_sentiment: 'Bullish',
    color: '#F40009',
  },
  {
    ticker: 'PEP',
    name: 'PepsiCo Inc.',
    type: 'Stock',
    category: 'stocks',
    region: 'US',
    country: 'United States',
    exchange: 'NASDAQ',
    currency: 'USD',
    sector: 'Consumer Staples',
    industry: 'Beverages - Non-Alcoholic',
    current_price: 172.80,
    day_change: 0.80,
    day_change_pct: 0.47,
    volume_24h: '4.8M',
    market_cap: '$237B',
    pe_ratio: 24.8,
    high_52w: 183.15,
    low_52w: 155.83,
    beta: 0.54,
    eps: 6.97,
    description: 'PepsiCo, Inc. engages in the manufacture, marketing, distribution, and sale of various beverages and convenient foods worldwide.',
    ai_summary: 'Frito-Lay snacks division and international beverage volume underpin defensive earnings.',
    ai_sentiment: 'Neutral',
    color: '#004B93',
  },
  {
    ticker: 'NKE',
    name: 'NIKE Inc.',
    type: 'Stock',
    category: 'stocks',
    region: 'US',
    country: 'United States',
    exchange: 'NYSE',
    currency: 'USD',
    sector: 'Consumer Discretionary',
    industry: 'Footwear & Accessories',
    current_price: 82.50,
    day_change: -1.10,
    day_change_pct: -1.32,
    volume_24h: '9.8M',
    market_cap: '$124B',
    pe_ratio: 24.2,
    high_52w: 123.39,
    low_52w: 70.75,
    beta: 1.10,
    eps: 3.41,
    description: 'NIKE, Inc. designs, develops, markets, and sells athletic footwear, apparel, equipment, and accessories worldwide.',
    ai_summary: 'Product innovation pipeline reset and direct-to-consumer wholesale partnership rebalancing.',
    ai_sentiment: 'Neutral',
    color: '#111111',
  },
  {
    ticker: 'DIS',
    name: 'The Walt Disney Company',
    type: 'Stock',
    category: 'stocks',
    region: 'US',
    country: 'United States',
    exchange: 'NYSE',
    currency: 'USD',
    sector: 'Entertainment',
    industry: 'Entertainment',
    current_price: 94.80,
    day_change: 1.20,
    day_change_pct: 1.28,
    volume_24h: '8.6M',
    market_cap: '$173B',
    pe_ratio: 38.4,
    high_52w: 123.74,
    low_52w: 78.73,
    beta: 1.34,
    eps: 2.47,
    description: 'The Walt Disney Company operates as an entertainment company worldwide, operating Parks, Experiences, Streaming, and Studios.',
    ai_summary: 'Disney+ direct-to-consumer streaming reaches profitability while Experiences parks segment delivers robust cash generation.',
    ai_sentiment: 'Bullish',
    color: '#113CCF',
  },

  // US Energy & Industrials
  {
    ticker: 'XOM',
    name: 'Exxon Mobil Corporation',
    type: 'Stock',
    category: 'stocks',
    region: 'US',
    country: 'United States',
    exchange: 'NYSE',
    currency: 'USD',
    sector: 'Energy',
    industry: 'Oil & Gas Integrated',
    current_price: 116.40,
    day_change: 1.10,
    day_change_pct: 0.95,
    volume_24h: '14.8M',
    market_cap: '$462B',
    pe_ratio: 14.2,
    high_52w: 123.75,
    low_52w: 95.77,
    beta: 0.96,
    eps: 8.20,
    description: 'Exxon Mobil Corporation explores for and produces crude oil and natural gas in the United States and internationally.',
    ai_summary: 'Pioneer Natural Resources acquisition expands premier low-cost Permian Basin production inventory.',
    ai_sentiment: 'Bullish',
    color: '#ED1B2D',
  },
  {
    ticker: 'CVX',
    name: 'Chevron Corporation',
    type: 'Stock',
    category: 'stocks',
    region: 'US',
    country: 'United States',
    exchange: 'NYSE',
    currency: 'USD',
    sector: 'Energy',
    industry: 'Oil & Gas Integrated',
    current_price: 146.20,
    day_change: 0.90,
    day_change_pct: 0.62,
    volume_24h: '7.2M',
    market_cap: '$268B',
    pe_ratio: 13.8,
    high_52w: 167.11,
    low_52w: 139.62,
    beta: 1.12,
    eps: 10.59,
    description: 'Chevron Corporation engages in integrated energy and chemicals operations internationally.',
    ai_summary: 'Hess acquisition adds high-margin offshore Guyana assets to cash flow profile.',
    ai_sentiment: 'Bullish',
    color: '#005480',
  },
  {
    ticker: 'COP',
    name: 'ConocoPhillips',
    type: 'Stock',
    category: 'stocks',
    region: 'US',
    country: 'United States',
    exchange: 'NYSE',
    currency: 'USD',
    sector: 'Energy',
    industry: 'Oil & Gas E&P',
    current_price: 109.80,
    day_change: 1.40,
    day_change_pct: 1.29,
    volume_24h: '5.4M',
    market_cap: '$128B',
    pe_ratio: 12.6,
    high_52w: 134.38,
    low_52w: 104.22,
    beta: 1.24,
    eps: 8.71,
    description: 'ConocoPhillips explores for, produces, transports, and markets crude oil, bitumen, natural gas, LNG, and NGLs.',
    ai_summary: 'Marathon Oil acquisition deepens low cost of supply shale positions.',
    ai_sentiment: 'Bullish',
    color: '#C8102E',
  },
  {
    ticker: 'CAT',
    name: 'Caterpillar Inc.',
    type: 'Stock',
    category: 'stocks',
    region: 'US',
    country: 'United States',
    exchange: 'NYSE',
    currency: 'USD',
    sector: 'Industrials',
    industry: 'Farm & Heavy Construction Machinery',
    current_price: 348.50,
    day_change: 4.20,
    day_change_pct: 1.22,
    volume_24h: '2.4M',
    market_cap: '$169B',
    pe_ratio: 16.5,
    high_52w: 391.87,
    low_52w: 223.76,
    beta: 1.15,
    eps: 21.12,
    description: 'Caterpillar Inc. manufactures and sells construction and mining equipment, diesel and natural gas engines, and industrial gas turbines.',
    ai_summary: 'Infrastructure spending bill execution and global energy transition mineral mining demand.',
    ai_sentiment: 'Bullish',
    color: '#FFCD11',
  },
  {
    ticker: 'GE',
    name: 'GE Aerospace',
    type: 'Stock',
    category: 'stocks',
    region: 'US',
    country: 'United States',
    exchange: 'NYSE',
    currency: 'USD',
    sector: 'Industrials',
    industry: 'Aerospace & Defense',
    current_price: 178.60,
    day_change: 2.80,
    day_change_pct: 1.59,
    volume_24h: '4.8M',
    market_cap: '$194B',
    pe_ratio: 36.8,
    high_52w: 194.20,
    low_52w: 83.40,
    beta: 1.22,
    eps: 4.85,
    description: 'GE Aerospace designs and produces commercial and military aircraft engines, integrated systems, and electric power systems.',
    ai_summary: 'Massive multi-decade commercial aircraft engine aftermarket servicing and CFM LEAP engine deliveries.',
    ai_sentiment: 'Bullish',
    color: '#005EB8',
  },
  {
    ticker: 'BA',
    name: 'The Boeing Company',
    type: 'Stock',
    category: 'stocks',
    region: 'US',
    country: 'United States',
    exchange: 'NYSE',
    currency: 'USD',
    sector: 'Industrials',
    industry: 'Aerospace & Defense',
    current_price: 158.20,
    day_change: -2.40,
    day_change_pct: -1.49,
    volume_24h: '6.2M',
    market_cap: '$97B',
    pe_ratio: null,
    high_52w: 267.54,
    low_52w: 148.10,
    beta: 1.48,
    eps: -4.20,
    description: 'The Boeing Company designs, develops, manufactures, sells, services, and supports commercial jetliners, defense aircraft, and space systems.',
    ai_summary: 'Leadership overhaul focused on manufacturing quality stability and 737 MAX production rate recovery.',
    ai_sentiment: 'Neutral',
    color: '#0033A0',
  },

  // US Healthcare & Pharma
  {
    ticker: 'LLY',
    name: 'Eli Lilly and Company',
    type: 'Stock',
    category: 'stocks',
    region: 'US',
    country: 'United States',
    exchange: 'NYSE',
    currency: 'USD',
    sector: 'Pharmaceuticals',
    industry: 'Drug Manufacturers - General',
    current_price: 924.50,
    day_change: 14.80,
    day_change_pct: 1.63,
    volume_24h: '3.1M',
    market_cap: '$878B',
    pe_ratio: 114.2,
    high_52w: 972.53,
    low_52w: 517.15,
    beta: 0.42,
    eps: 8.10,
    description: 'Eli Lilly and Company discovers, develops, and markets human pharmaceuticals worldwide, including treatments for diabetes, obesity, oncology, and immunology.',
    ai_summary: 'Unprecedented demand for GLP-1 blockbuster treatments Mounjaro and Zepbound drives world-leading pharma market valuation.',
    ai_sentiment: 'Bullish',
    color: '#D52B1E',
  },
  {
    ticker: 'JNJ',
    name: 'Johnson & Johnson',
    type: 'Stock',
    category: 'stocks',
    region: 'US',
    country: 'United States',
    exchange: 'NYSE',
    currency: 'USD',
    sector: 'Healthcare',
    industry: 'Drug Manufacturers - General',
    current_price: 164.80,
    day_change: 0.60,
    day_change_pct: 0.37,
    volume_24h: '6.4M',
    market_cap: '$396B',
    pe_ratio: 24.1,
    high_52w: 175.97,
    low_52w: 143.16,
    beta: 0.54,
    eps: 6.84,
    description: 'Johnson & Johnson researches, develops, manufactures, and sells healthcare products worldwide, operating through Innovative Medicine and MedTech.',
    ai_summary: 'MedTech cardiovascular surgical robotic growth and oncology pharmaceuticals pipeline.',
    ai_sentiment: 'Bullish',
    color: '#D51900',
  },
  {
    ticker: 'MRK',
    name: 'Merck & Co. Inc.',
    type: 'Stock',
    category: 'stocks',
    region: 'US',
    country: 'United States',
    exchange: 'NYSE',
    currency: 'USD',
    sector: 'Healthcare',
    industry: 'Drug Manufacturers - General',
    current_price: 118.40,
    day_change: 0.90,
    day_change_pct: 0.77,
    volume_24h: '7.8M',
    market_cap: '$299B',
    pe_ratio: 21.8,
    high_52w: 134.63,
    low_52w: 99.14,
    beta: 0.41,
    eps: 5.43,
    description: 'Merck & Co., Inc. operates as a healthcare company worldwide, providing human health pharmaceuticals and animal health products.',
    ai_summary: 'Keytruda oncology revenue dominance and cardiometabolic pipeline expansion with Winrevair.',
    ai_sentiment: 'Bullish',
    color: '#00857C',
  },
  {
    ticker: 'PFE',
    name: 'Pfizer Inc.',
    type: 'Stock',
    category: 'stocks',
    region: 'US',
    country: 'United States',
    exchange: 'NYSE',
    currency: 'USD',
    sector: 'Healthcare',
    industry: 'Drug Manufacturers - General',
    current_price: 28.60,
    day_change: 0.20,
    day_change_pct: 0.70,
    volume_24h: '28.4M',
    market_cap: '$162B',
    pe_ratio: 18.2,
    high_52w: 36.88,
    low_52w: 25.20,
    beta: 0.65,
    eps: 1.57,
    description: 'Pfizer Inc. discovers, develops, manufactures, markets, distributes, and sells biopharmaceutical products worldwide.',
    ai_summary: 'Seagen oncology acquisition integration and high 5.8% dividend yield attract value investors.',
    ai_sentiment: 'Neutral',
    color: '#0000FF',
  },
  {
    ticker: 'ABBV',
    name: 'AbbVie Inc.',
    type: 'Stock',
    category: 'stocks',
    region: 'US',
    country: 'United States',
    exchange: 'NYSE',
    currency: 'USD',
    sector: 'Healthcare',
    industry: 'Drug Manufacturers - General',
    current_price: 192.40,
    day_change: 1.80,
    day_change_pct: 0.94,
    volume_24h: '4.2M',
    market_cap: '$340B',
    pe_ratio: 58.2,
    high_52w: 198.70,
    low_52w: 137.24,
    beta: 0.58,
    eps: 3.31,
    description: 'AbbVie Inc. discovers, develops, manufactures, and sells pharmaceuticals worldwide.',
    ai_summary: 'Skyrizi and Rinvoq immunology therapies successfully offset Humira biosimilar competition.',
    ai_sentiment: 'Bullish',
    color: '#002B49',
  },
  {
    ticker: 'UNH',
    name: 'UnitedHealth Group Inc.',
    type: 'Stock',
    category: 'stocks',
    region: 'US',
    country: 'United States',
    exchange: 'NYSE',
    currency: 'USD',
    sector: 'Healthcare',
    industry: 'Healthcare Plans',
    current_price: 584.20,
    day_change: 4.80,
    day_change_pct: 0.83,
    volume_24h: '2.9M',
    market_cap: '$538B',
    pe_ratio: 38.6,
    high_52w: 606.35,
    low_52w: 436.38,
    beta: 0.62,
    eps: 15.13,
    description: 'UnitedHealth Group Incorporated operates as a diversified healthcare company in the United States, providing health insurance and Optum health services.',
    ai_summary: 'Optum health services integration and Medicare Advantage demographic growth tailwinds.',
    ai_sentiment: 'Bullish',
    color: '#002677',
  },

  // =========================================================================
  // 2. CANADIAN EQUITIES (TSX Leaders)
  // =========================================================================
  {
    ticker: 'RY',
    name: 'Royal Bank of Canada',
    type: 'Stock',
    category: 'stocks',
    region: 'Canada',
    country: 'Canada',
    exchange: 'TSX',
    currency: 'CAD',
    sector: 'Financial Services',
    industry: 'Banks - Diversified',
    current_price: 158.40,
    day_change: 1.20,
    day_change_pct: 0.76,
    volume_24h: '3.4M',
    market_cap: '$224B',
    pe_ratio: 13.8,
    high_52w: 164.20,
    low_52w: 118.50,
    beta: 0.82,
    eps: 11.48,
    description: 'Royal Bank of Canada operates as a diversified financial service company worldwide, offering personal and commercial banking, wealth management, and capital markets.',
    ai_summary: 'Canada’s largest bank by market capitalization; HSBC Canada acquisition bolsters commercial banking dominance.',
    ai_sentiment: 'Bullish',
    color: '#0051A5',
  },
  {
    ticker: 'TD',
    name: 'Toronto-Dominion Bank',
    type: 'Stock',
    category: 'stocks',
    region: 'Canada',
    country: 'Canada',
    exchange: 'TSX',
    currency: 'CAD',
    sector: 'Financial Services',
    industry: 'Banks - Diversified',
    current_price: 78.50,
    day_change: 0.60,
    day_change_pct: 0.77,
    volume_24h: '6.2M',
    market_cap: '$138B',
    pe_ratio: 12.4,
    high_52w: 87.80,
    low_52w: 73.20,
    beta: 0.88,
    eps: 6.33,
    description: 'The Toronto-Dominion Bank provides various personal and commercial banking products and services in Canada, the United States, and internationally.',
    ai_summary: 'Extensive retail banking network across eastern North America and high 5%+ dividend yield.',
    ai_sentiment: 'Neutral',
    color: '#008A00',
  },
  {
    ticker: 'ENB',
    name: 'Enbridge Inc.',
    type: 'Stock',
    category: 'stocks',
    region: 'Canada',
    country: 'Canada',
    exchange: 'TSX',
    currency: 'CAD',
    sector: 'Energy Infrastructure',
    industry: 'Oil & Gas Midstream',
    current_price: 52.80,
    day_change: 0.40,
    day_change_pct: 0.76,
    volume_24h: '8.4M',
    market_cap: '$112B',
    pe_ratio: 18.5,
    high_52w: 54.90,
    low_52w: 43.10,
    beta: 0.75,
    eps: 2.85,
    description: 'Enbridge Inc. operates as an energy infrastructure company, managing the world’s longest crude oil and liquid petroleum transportation system.',
    ai_summary: 'Regulated utility-like cash flows, long-term contracted pipeline assets, and reliable 6.8% dividend yield.',
    ai_sentiment: 'Bullish',
    color: '#FFCC00',
  },
  {
    ticker: 'SHOP',
    name: 'Shopify Inc.',
    type: 'Stock',
    category: 'stocks',
    region: 'Canada',
    country: 'Canada',
    exchange: 'TSX',
    currency: 'CAD',
    sector: 'E-Commerce Software',
    industry: 'Software - Application',
    current_price: 74.60,
    day_change: 2.80,
    day_change_pct: 3.90,
    volume_24h: '11.8M',
    market_cap: '$96B',
    pe_ratio: 72.4,
    high_52w: 91.57,
    low_52w: 48.56,
    beta: 2.10,
    eps: 1.03,
    description: 'Shopify Inc. provides a commerce platform and services in Canada, the United States, Europe, the Middle East, Africa, the Asia Pacific, and Latin America.',
    ai_summary: 'Merchant solutions take rate expansion, enterprise Shop Pay adoption, and accelerating free cash flow conversion.',
    ai_sentiment: 'Bullish',
    color: '#95BF47',
  },
  {
    ticker: 'CNR',
    name: 'Canadian National Railway',
    type: 'Stock',
    category: 'stocks',
    region: 'Canada',
    country: 'Canada',
    exchange: 'TSX',
    currency: 'CAD',
    sector: 'Transportation',
    industry: 'Railroads',
    current_price: 156.20,
    day_change: 0.90,
    day_change_pct: 0.58,
    volume_24h: '1.9M',
    market_cap: '$98B',
    pe_ratio: 19.8,
    high_52w: 178.40,
    low_52w: 144.20,
    beta: 0.72,
    eps: 7.89,
    description: 'Canadian National Railway Company engages in the rail and related transportation business across Canada and the United States.',
    ai_summary: 'Unique tri-coastal rail network (Pacific, Atlantic, Gulf of Mexico) with high barriers to entry.',
    ai_sentiment: 'Bullish',
    color: '#E31B23',
  },

  // =========================================================================
  // 3. EUROPEAN EQUITIES (Euronext, LSE, XETRA, SIX)
  // =========================================================================
  {
    ticker: 'ASML',
    name: 'ASML Holding N.V.',
    type: 'Stock',
    category: 'stocks',
    region: 'Europe',
    country: 'Netherlands',
    exchange: 'EURONEXT',
    currency: 'EUR',
    sector: 'Semiconductors',
    industry: 'Semiconductor Equipment',
    current_price: 842.50,
    day_change: 18.20,
    day_change_pct: 2.21,
    volume_24h: '2.4M',
    market_cap: '$338B',
    pe_ratio: 44.5,
    high_52w: 1020.00,
    low_52w: 540.00,
    beta: 1.42,
    eps: 18.93,
    description: 'ASML Holding N.V. develops, produces, markets, sells, and services advanced semiconductor equipment systems consisting of lithography, metrology, and inspection systems.',
    ai_summary: 'Monopolistic global supplier of Extreme Ultraviolet (EUV) photolithography machines essential for advanced AI chip fabrication.',
    ai_sentiment: 'Bullish',
    color: '#00263E',
  },
  {
    ticker: 'SAP',
    name: 'SAP SE',
    type: 'Stock',
    category: 'stocks',
    region: 'Europe',
    country: 'Germany',
    exchange: 'DAX',
    currency: 'EUR',
    sector: 'Enterprise Software',
    industry: 'Software - Application',
    current_price: 198.40,
    day_change: 3.10,
    day_change_pct: 1.59,
    volume_24h: '3.1M',
    market_cap: '$232B',
    pe_ratio: 38.6,
    high_52w: 202.40,
    low_52w: 120.50,
    beta: 1.05,
    eps: 5.14,
    description: 'SAP SE operates as an enterprise application software company, offering SAP S/4HANA ERP, supply chain management, and business AI solutions.',
    ai_summary: 'Cloud revenue acceleration exceeding 25% YoY and Business AI integration across Fortune 500 corporate operations.',
    ai_sentiment: 'Bullish',
    color: '#008FD3',
  },
  {
    ticker: 'NESN',
    name: 'Nestlé S.A.',
    type: 'Stock',
    category: 'stocks',
    region: 'Europe',
    country: 'Switzerland',
    exchange: 'SIX',
    currency: 'CHF',
    sector: 'Consumer Staples',
    industry: 'Packaged Foods',
    current_price: 88.60,
    day_change: 0.40,
    day_change_pct: 0.45,
    volume_24h: '4.8M',
    market_cap: '$234B',
    pe_ratio: 21.2,
    high_52w: 108.40,
    low_52w: 84.20,
    beta: 0.48,
    eps: 4.18,
    description: 'Nestlé S.A. operates as a food and beverage company worldwide, offering coffee, pet care, nutrition, and dairy products.',
    ai_summary: 'Global household staple brand dominance including Nespresso, Purina, and Gerber with premium margins.',
    ai_sentiment: 'Neutral',
    color: '#005CA9',
  },
  {
    ticker: 'NOVN',
    name: 'Novartis AG',
    type: 'Stock',
    category: 'stocks',
    region: 'Europe',
    country: 'Switzerland',
    exchange: 'SIX',
    currency: 'CHF',
    sector: 'Pharmaceuticals',
    industry: 'Drug Manufacturers - General',
    current_price: 98.40,
    day_change: 0.80,
    day_change_pct: 0.82,
    volume_24h: '3.6M',
    market_cap: '$204B',
    pe_ratio: 16.4,
    high_52w: 103.50,
    low_52w: 82.10,
    beta: 0.52,
    eps: 6.00,
    description: 'Novartis AG researches, develops, manufactures, and markets healthcare products worldwide, specializing in cardiovascular, immunology, and oncology.',
    ai_summary: 'Entresto cardiovascular and Kesimpta multiple sclerosis therapies drive core operating income expansion.',
    ai_sentiment: 'Bullish',
    color: '#004B87',
  },
  {
    ticker: 'LVMH',
    name: 'LVMH Moët Hennessy Louis Vuitton',
    type: 'Stock',
    category: 'stocks',
    region: 'Europe',
    country: 'France',
    exchange: 'EURONEXT',
    currency: 'EUR',
    sector: 'Luxury Goods',
    industry: 'Luxury Goods',
    current_price: 684.20,
    day_change: 7.80,
    day_change_pct: 1.15,
    volume_24h: '1.2M',
    market_cap: '$342B',
    pe_ratio: 22.4,
    high_52w: 885.00,
    low_52w: 620.00,
    beta: 1.18,
    eps: 30.54,
    description: 'LVMH Moët Hennessy - Louis Vuitton, Société Européenne operates as a luxury goods company worldwide, spanning fashion, leather goods, and spirits.',
    ai_summary: 'Unrivaled global luxury portfolio including Louis Vuitton, Christian Dior, Tiffany & Co., and Moët & Chandon.',
    ai_sentiment: 'Bullish',
    color: '#1A1A1A',
  },
  {
    ticker: 'AZN',
    name: 'AstraZeneca PLC',
    type: 'Stock',
    category: 'stocks',
    region: 'Europe',
    country: 'United Kingdom',
    exchange: 'LSE',
    currency: 'GBP',
    sector: 'Pharmaceuticals',
    industry: 'Drug Manufacturers - General',
    current_price: 124.50,
    day_change: 1.40,
    day_change_pct: 1.14,
    volume_24h: '3.8M',
    market_cap: '$244B',
    pe_ratio: 35.8,
    high_52w: 132.80,
    low_52w: 96.40,
    beta: 0.58,
    eps: 3.48,
    description: 'AstraZeneca PLC discovers, develops, manufactures, and commercializes prescription medicines for oncology, rare diseases, and cardiovascular ailments.',
    ai_summary: 'Tagrisso, Enhertu, and Farxiga therapeutics generate double-digit biopharma revenue growth.',
    ai_sentiment: 'Bullish',
    color: '#EB0029',
  },
  {
    ticker: 'SHEL',
    name: 'Shell PLC',
    type: 'Stock',
    category: 'stocks',
    region: 'Europe',
    country: 'United Kingdom',
    exchange: 'LSE',
    currency: 'GBP',
    sector: 'Energy',
    industry: 'Oil & Gas Integrated',
    current_price: 68.20,
    day_change: 0.70,
    day_change_pct: 1.04,
    volume_24h: '7.9M',
    market_cap: '$218B',
    pe_ratio: 11.2,
    high_52w: 73.80,
    low_52w: 58.40,
    beta: 0.92,
    eps: 6.09,
    description: 'Shell plc operates as an energy and petrochemical company worldwide, operating Integrated Gas, Upstream, and Marketing.',
    ai_summary: 'Global leadership in Liquefied Natural Gas (LNG) trading and disciplined share buyback execution.',
    ai_sentiment: 'Bullish',
    color: '#FFD500',
  },

  // =========================================================================
  // 4. ASIAN EQUITIES (Tokyo, Taipei, Hong Kong, Mumbai)
  // =========================================================================
  {
    ticker: 'TSM',
    name: 'Taiwan Semiconductor Manufacturing Co.',
    type: 'Stock',
    category: 'stocks',
    region: 'Asia',
    country: 'Taiwan',
    exchange: 'NYSE / TWSE',
    currency: 'USD',
    sector: 'Semiconductors',
    industry: 'Semiconductors',
    current_price: 172.40,
    day_change: 4.80,
    day_change_pct: 2.86,
    volume_24h: '18.4M',
    market_cap: '$894B',
    pe_ratio: 31.2,
    high_52w: 193.47,
    low_52w: 84.50,
    beta: 1.35,
    eps: 5.53,
    description: 'Taiwan Semiconductor Manufacturing Company Limited manufactures and sells integrated circuits and semiconductor products used in computers, mobile, and AI hardware.',
    ai_summary: 'Foundry market share leader above 60% with exclusive 3nm and 2nm advanced node manufacturing capacity for Apple, NVIDIA, and AMD.',
    ai_sentiment: 'Bullish',
    color: '#002B49',
  },
  {
    ticker: 'BABA',
    name: 'Alibaba Group Holding Ltd.',
    type: 'Stock',
    category: 'stocks',
    region: 'Asia',
    country: 'China',
    exchange: 'NYSE / HKEX',
    currency: 'USD',
    sector: 'E-Commerce & Cloud',
    industry: 'Internet Retail',
    current_price: 84.50,
    day_change: 2.10,
    day_change_pct: 2.55,
    volume_24h: '32.1M',
    market_cap: '$198B',
    pe_ratio: 14.8,
    high_52w: 92.40,
    low_52w: 68.05,
    beta: 0.95,
    eps: 5.71,
    description: 'Alibaba Group Holding Limited provides technology infrastructure and marketing reach to help merchants, brands, and businesses leverage the Internet.',
    ai_summary: 'Taobao/Tmall e-commerce cash flow generation and Alibaba Cloud AI infrastructure adoption.',
    ai_sentiment: 'Bullish',
    color: '#FF6000',
  },
  {
    ticker: 'TM',
    name: 'Toyota Motor Corporation',
    type: 'Stock',
    category: 'stocks',
    region: 'Asia',
    country: 'Japan',
    exchange: 'TSE / NYSE',
    currency: 'USD',
    sector: 'Automotive',
    industry: 'Auto Manufacturers',
    current_price: 188.40,
    day_change: 1.90,
    day_change_pct: 1.02,
    volume_24h: '2.8M',
    market_cap: '$282B',
    pe_ratio: 8.5,
    high_52w: 255.40,
    low_52w: 168.20,
    beta: 0.74,
    eps: 22.16,
    description: 'Toyota Motor Corporation designs, manufactures, assembles, and sells passenger vehicles, minivans, commercial vehicles, and related parts globally.',
    ai_summary: 'World’s highest-volume vehicle manufacturer; hybrid powertrain leadership captures strong consumer demand.',
    ai_sentiment: 'Bullish',
    color: '#EB0A1E',
  },
  {
    ticker: 'SONY',
    name: 'Sony Group Corporation',
    type: 'Stock',
    category: 'stocks',
    region: 'Asia',
    country: 'Japan',
    exchange: 'TSE / NYSE',
    currency: 'USD',
    sector: 'Consumer Electronics & Gaming',
    industry: 'Consumer Electronics',
    current_price: 94.20,
    day_change: 1.40,
    day_change_pct: 1.51,
    volume_24h: '1.8M',
    market_cap: '$116B',
    pe_ratio: 17.5,
    high_52w: 100.80,
    low_52w: 78.40,
    beta: 0.88,
    eps: 5.38,
    description: 'Sony Group Corporation designs, develops, produces, and sells electronic equipment, instruments, gaming consoles, software, and music/film content.',
    ai_summary: 'PlayStation ecosystem, image sensor market dominance, and entertainment IP licensing.',
    ai_sentiment: 'Bullish',
    color: '#000000',
  },
  {
    ticker: 'INFY',
    name: 'Infosys Limited',
    type: 'Stock',
    category: 'stocks',
    region: 'Asia',
    country: 'India',
    exchange: 'NSE / NYSE',
    currency: 'USD',
    sector: 'IT Consulting & Services',
    industry: 'Information Technology Services',
    current_price: 22.80,
    day_change: 0.35,
    day_change_pct: 1.56,
    volume_24h: '14.2M',
    market_cap: '$94B',
    pe_ratio: 28.4,
    high_52w: 23.40,
    low_52w: 15.80,
    beta: 0.92,
    eps: 0.80,
    description: 'Infosys Limited provides consulting, technology, outsourcing, and next-generation digital services in North America, Europe, India, and internationally.',
    ai_summary: 'Large enterprise digital transformation deals and Topaz generative AI suite adoption.',
    ai_sentiment: 'Bullish',
    color: '#007CC3',
  },
  {
    ticker: 'HDB',
    name: 'HDFC Bank Limited',
    type: 'Stock',
    category: 'stocks',
    region: 'Asia',
    country: 'India',
    exchange: 'NSE / NYSE',
    currency: 'USD',
    sector: 'Financial Services',
    industry: 'Banks - Regional',
    current_price: 58.40,
    day_change: 0.80,
    day_change_pct: 1.39,
    volume_24h: '4.2M',
    market_cap: '$148B',
    pe_ratio: 18.2,
    high_52w: 68.20,
    low_52w: 52.40,
    beta: 0.85,
    eps: 3.21,
    description: 'HDFC Bank Limited provides various banking and financial services to individuals and businesses in India.',
    ai_summary: 'India’s largest private sector bank; strong credit growth and expanding branch network.',
    ai_sentiment: 'Bullish',
    color: '#004C8F',
  },

  // =========================================================================
  // 5. LATIN AMERICAN & EMERGING MARKETS EQUITIES
  // =========================================================================
  {
    ticker: 'VALE',
    name: 'Vale S.A.',
    type: 'Stock',
    category: 'stocks',
    region: 'Latin America',
    country: 'Brazil',
    exchange: 'B3 / NYSE',
    currency: 'USD',
    sector: 'Basic Materials',
    industry: 'Industrial Metals & Minerals',
    current_price: 10.80,
    day_change: 0.20,
    day_change_pct: 1.89,
    volume_24h: '24.8M',
    market_cap: '$48B',
    pe_ratio: 5.8,
    high_52w: 15.90,
    low_52w: 9.80,
    beta: 1.15,
    eps: 1.86,
    description: 'Vale S.A. produces and sells iron ore and iron ore pellets for use as raw materials in steelmaking in Brazil and internationally.',
    ai_summary: 'Low-cost Carajás iron ore production and copper/nickel energy transition metals portfolio.',
    ai_sentiment: 'Neutral',
    color: '#00857C',
  },
  {
    ticker: 'PBR',
    name: 'Petróleo Brasileiro S.A. - Petrobras',
    type: 'Stock',
    category: 'stocks',
    region: 'Latin America',
    country: 'Brazil',
    exchange: 'B3 / NYSE',
    currency: 'USD',
    sector: 'Energy',
    industry: 'Oil & Gas Integrated',
    current_price: 14.20,
    day_change: 0.30,
    day_change_pct: 2.16,
    volume_24h: '21.5M',
    market_cap: '$92B',
    pe_ratio: 4.8,
    high_52w: 17.80,
    low_52w: 12.10,
    beta: 1.30,
    eps: 2.96,
    description: 'Petróleo Brasileiro S.A. - Petrobras explores, produces, and sells oil and gas in Brazil and internationally.',
    ai_summary: 'Deepwater pre-salt crude reserves with world-leading lifting costs under $35 per barrel.',
    ai_sentiment: 'Bullish',
    color: '#008542',
  },
  {
    ticker: 'NU',
    name: 'Nu Holdings Ltd.',
    type: 'Stock',
    category: 'stocks',
    region: 'Latin America',
    country: 'Brazil',
    exchange: 'NYSE',
    currency: 'USD',
    sector: 'Fintech & Digital Banking',
    industry: 'Banks - Regional',
    current_price: 14.80,
    day_change: 0.65,
    day_change_pct: 4.59,
    volume_24h: '42.1M',
    market_cap: '$71B',
    pe_ratio: 36.4,
    high_52w: 15.60,
    low_52w: 7.20,
    beta: 1.25,
    eps: 0.41,
    description: 'Nu Holdings Ltd. operates a digital banking platform in Brazil, Mexico, and Colombia under the Nubank brand.',
    ai_summary: 'Surpassed 100 million active banking customers with industry-low customer acquisition cost and expanding ROE.',
    ai_sentiment: 'Bullish',
    color: '#820AD1',
  },
  {
    ticker: 'MELI',
    name: 'MercadoLibre Inc.',
    type: 'Stock',
    category: 'stocks',
    region: 'Latin America',
    country: 'Argentina',
    exchange: 'NASDAQ',
    currency: 'USD',
    sector: 'E-Commerce & Fintech',
    industry: 'Internet Retail',
    current_price: 1980.50,
    day_change: 42.00,
    day_change_pct: 2.17,
    volume_24h: '680K',
    market_cap: '$100B',
    pe_ratio: 68.2,
    high_52w: 2050.00,
    low_52w: 1180.00,
    beta: 1.48,
    eps: 29.04,
    description: 'MercadoLibre, Inc. operates online commerce platforms and fintech services in Latin America.',
    ai_summary: 'Dominant Latin American commerce and Mercado Pago fintech ecosystem with 35%+ revenue growth.',
    ai_sentiment: 'Bullish',
    color: '#FFE600',
  },

  // =========================================================================
  // 6. MAJOR ETFS (Index, Sector, & Thematic)
  // =========================================================================
  {
    ticker: 'SPY',
    name: 'SPDR S&P 500 ETF Trust',
    type: 'ETF',
    category: 'etfs',
    region: 'US',
    country: 'United States',
    exchange: 'NYSE Arca',
    currency: 'USD',
    sector: 'Broad Market Equity',
    current_price: 554.80,
    day_change: 3.40,
    day_change_pct: 0.62,
    volume_24h: '52.4M',
    market_cap: '$570B',
    pe_ratio: 27.4,
    high_52w: 565.16,
    low_52w: 409.21,
    beta: 1.00,
    eps: 20.25,
    description: 'The SPDR S&P 500 ETF Trust corresponds generally to the price and yield performance of the S&P 500 Index, representing 500 large-cap US companies.',
    ai_summary: 'Core institutional benchmark tracking large-cap US economic leadership with ultra-low expense ratio.',
    ai_sentiment: 'Bullish',
    color: '#002B49',
  },
  {
    ticker: 'QQQ',
    name: 'Invesco QQQ Trust',
    type: 'ETF',
    category: 'etfs',
    region: 'US',
    country: 'United States',
    exchange: 'NASDAQ',
    currency: 'USD',
    sector: 'Large-Cap Growth & Tech',
    current_price: 482.30,
    day_change: 4.90,
    day_change_pct: 1.03,
    volume_24h: '38.2M',
    market_cap: '$285B',
    pe_ratio: 31.8,
    high_52w: 503.52,
    low_52w: 351.36,
    beta: 1.18,
    eps: 15.17,
    description: 'Invesco QQQ tracks the Nasdaq-100 Index, holding 100 of the largest non-financial companies listed on NASDAQ.',
    ai_summary: 'Concentrated exposure to AI, cloud software, digital advertising, and consumer technology innovators.',
    ai_sentiment: 'Bullish',
    color: '#005A9C',
  },
  {
    ticker: 'VOO',
    name: 'Vanguard S&P 500 ETF',
    type: 'ETF',
    category: 'etfs',
    region: 'US',
    country: 'United States',
    exchange: 'NYSE Arca',
    currency: 'USD',
    sector: 'Broad Market Equity',
    current_price: 508.60,
    day_change: 3.10,
    day_change_pct: 0.61,
    volume_24h: '4.8M',
    market_cap: '$480B',
    pe_ratio: 27.2,
    high_52w: 518.20,
    low_52w: 375.40,
    beta: 1.00,
    eps: 18.70,
    description: 'Vanguard S&P 500 ETF invests in stocks in the S&P 500 Index, representing 500 of the largest US companies with an ultra-low 0.03% expense ratio.',
    ai_summary: 'Premier ultra-low cost passive indexing vehicle favored for long-term compounding.',
    ai_sentiment: 'Bullish',
    color: '#9E1B32',
  },
  {
    ticker: 'VTI',
    name: 'Vanguard Total Stock Market ETF',
    type: 'ETF',
    category: 'etfs',
    region: 'US',
    country: 'United States',
    exchange: 'NYSE Arca',
    currency: 'USD',
    sector: 'Total US Market',
    current_price: 272.40,
    day_change: 1.80,
    day_change_pct: 0.66,
    volume_24h: '3.2M',
    market_cap: '$410B',
    pe_ratio: 26.5,
    high_52w: 278.40,
    low_52w: 202.10,
    beta: 1.02,
    eps: 10.28,
    description: 'Vanguard Total Stock Market ETF tracks the CRSP US Total Market Index, representing approximately 100% of the investable US stock market.',
    ai_summary: 'Comprehensive diversification across large, mid, small, and micro-cap US equities.',
    ai_sentiment: 'Bullish',
    color: '#9E1B32',
  },
  {
    ticker: 'IWM',
    name: 'iShares Russell 2000 ETF',
    type: 'ETF',
    category: 'etfs',
    region: 'US',
    country: 'United States',
    exchange: 'NYSE Arca',
    currency: 'USD',
    sector: 'Small-Cap Equity',
    current_price: 214.20,
    day_change: 2.80,
    day_change_pct: 1.32,
    volume_24h: '28.5M',
    market_cap: '$68B',
    pe_ratio: 22.4,
    high_52w: 228.40,
    low_52w: 161.20,
    beta: 1.25,
    eps: 9.56,
    description: 'The iShares Russell 2000 ETF seeks to track the investment results of an index composed of small-capitalization U.S. equities.',
    ai_summary: 'High sensitivity to interest rate cutting cycles and domestic economic expansion.',
    ai_sentiment: 'Bullish',
    color: '#000000',
  },
  {
    ticker: 'DIA',
    name: 'SPDR Dow Jones Industrial Average ETF',
    type: 'ETF',
    category: 'etfs',
    region: 'US',
    country: 'United States',
    exchange: 'NYSE Arca',
    currency: 'USD',
    sector: 'Blue Chip Value',
    current_price: 406.80,
    day_change: 1.90,
    day_change_pct: 0.47,
    volume_24h: '3.6M',
    market_cap: '$34B',
    pe_ratio: 21.2,
    high_52w: 414.20,
    low_52w: 323.50,
    beta: 0.88,
    eps: 19.19,
    description: 'The SPDR Dow Jones Industrial Average ETF Trust seeks to provide investment results that correspond generally to the price and yield performance of the DJIA.',
    ai_summary: 'Price-weighted basket of 30 premier US industrial, financial, and consumer blue-chips.',
    ai_sentiment: 'Bullish',
    color: '#002B49',
  },
  {
    ticker: 'XLK',
    name: 'Technology Select Sector SPDR Fund',
    type: 'ETF',
    category: 'etfs',
    region: 'US',
    country: 'United States',
    exchange: 'NYSE Arca',
    currency: 'USD',
    sector: 'Technology',
    current_price: 228.50,
    day_change: 3.20,
    day_change_pct: 1.42,
    volume_24h: '6.4M',
    market_cap: '$72B',
    pe_ratio: 35.4,
    high_52w: 240.50,
    low_52w: 162.10,
    beta: 1.28,
    eps: 6.45,
    description: 'XLK tracks an index of S&P 500 technology companies, holding Apple, Microsoft, NVIDIA, and top enterprise semiconductor leaders.',
    ai_summary: 'Direct exposure to enterprise artificial intelligence hardware and software infrastructure.',
    ai_sentiment: 'Bullish',
    color: '#00704A',
  },
  {
    ticker: 'XLF',
    name: 'Financial Select Sector SPDR Fund',
    type: 'ETF',
    category: 'etfs',
    region: 'US',
    country: 'United States',
    exchange: 'NYSE Arca',
    currency: 'USD',
    sector: 'Financials',
    current_price: 44.80,
    day_change: 0.45,
    day_change_pct: 1.01,
    volume_24h: '38.2M',
    market_cap: '$42B',
    pe_ratio: 16.8,
    high_52w: 46.20,
    low_52w: 31.80,
    beta: 1.10,
    eps: 2.67,
    description: 'XLF tracks an index of financial services companies in the S&P 500, including commercial banks, insurance, and investment banks.',
    ai_summary: 'Capital markets recovery and robust net interest margins support financial sector returns.',
    ai_sentiment: 'Bullish',
    color: '#002B49',
  },
  {
    ticker: 'XLE',
    name: 'Energy Select Sector SPDR Fund',
    type: 'ETF',
    category: 'etfs',
    region: 'US',
    country: 'United States',
    exchange: 'NYSE Arca',
    currency: 'USD',
    sector: 'Energy',
    current_price: 88.40,
    day_change: 0.80,
    day_change_pct: 0.91,
    volume_24h: '14.2M',
    market_cap: '$38B',
    pe_ratio: 13.5,
    high_52w: 98.40,
    low_52w: 78.20,
    beta: 1.15,
    eps: 6.55,
    description: 'XLE tracks an index of energy companies in the S&P 500, holding Exxon Mobil, Chevron, and leading energy service providers.',
    ai_summary: 'Generous shareholder dividend payouts and free cash flow yields in traditional energy.',
    ai_sentiment: 'Bullish',
    color: '#D52B1E',
  },
  {
    ticker: 'XLV',
    name: 'Health Care Select Sector SPDR Fund',
    type: 'ETF',
    category: 'etfs',
    region: 'US',
    country: 'United States',
    exchange: 'NYSE Arca',
    currency: 'USD',
    sector: 'Healthcare',
    current_price: 148.60,
    day_change: 0.90,
    day_change_pct: 0.61,
    volume_24h: '7.8M',
    market_cap: '$41B',
    pe_ratio: 24.2,
    high_52w: 154.20,
    low_52w: 124.80,
    beta: 0.68,
    eps: 6.14,
    description: 'XLV tracks healthcare companies in the S&P 500 across pharmaceuticals, medical equipment, and healthcare providers.',
    ai_summary: 'Defensive cash flow profile combined with biopharma innovation in obesity and oncology.',
    ai_sentiment: 'Bullish',
    color: '#00857C',
  },
  {
    ticker: 'EEM',
    name: 'iShares MSCI Emerging Markets ETF',
    type: 'ETF',
    category: 'etfs',
    region: 'Emerging Markets',
    country: 'Global',
    exchange: 'NYSE Arca',
    currency: 'USD',
    sector: 'Emerging Markets',
    current_price: 43.80,
    day_change: 0.65,
    day_change_pct: 1.51,
    volume_24h: '34.2M',
    market_cap: '$22B',
    pe_ratio: 14.5,
    high_52w: 46.20,
    low_52w: 37.10,
    beta: 0.92,
    eps: 3.02,
    description: 'EEM tracks an index of large and mid-sized companies in emerging markets including Taiwan, China, India, and Brazil.',
    ai_summary: 'Broad emerging market growth and global technology supply chain participation.',
    ai_sentiment: 'Bullish',
    color: '#000000',
  },

  // =========================================================================
  // 7. MAJOR GLOBAL INDICES
  // =========================================================================
  {
    ticker: 'SPX',
    name: 'S&P 500 Index',
    type: 'Index',
    category: 'indices',
    region: 'US',
    country: 'United States',
    exchange: 'INDEX',
    currency: 'USD',
    sector: 'US Large Cap',
    current_price: 5554.20,
    day_change: 34.10,
    day_change_pct: 0.62,
    volume_24h: '2.4B',
    market_cap: '$46.8T',
    pe_ratio: 27.5,
    high_52w: 5669.67,
    low_52w: 4103.78,
    beta: 1.00,
    eps: 202.00,
    description: 'The Standard and Poor’s 500 is a stock market index tracking the stock performance of 500 of the largest companies listed on stock exchanges in the United States.',
    ai_summary: 'Primary barometer of the overall US equity market.',
    ai_sentiment: 'Bullish',
    color: '#002B49',
  },
  {
    ticker: 'NDX',
    name: 'Nasdaq-100 Index',
    type: 'Index',
    category: 'indices',
    region: 'US',
    country: 'United States',
    exchange: 'INDEX',
    currency: 'USD',
    sector: 'US Tech & Growth',
    current_price: 19520.40,
    day_change: 185.20,
    day_change_pct: 0.96,
    volume_24h: '1.2B',
    market_cap: '$22.4T',
    pe_ratio: 32.1,
    high_52w: 20690.97,
    low_52w: 14058.33,
    beta: 1.20,
    eps: 608.10,
    description: 'The Nasdaq-100 is a stock market index made up of 100 of the largest non-financial companies listed on the Nasdaq stock exchange.',
    ai_summary: 'World-leading technology innovation and enterprise digital transformation benchmark.',
    ai_sentiment: 'Bullish',
    color: '#005A9C',
  },
  {
    ticker: 'DJIA',
    name: 'Dow Jones Industrial Average',
    type: 'Index',
    category: 'indices',
    region: 'US',
    country: 'United States',
    exchange: 'INDEX',
    currency: 'USD',
    sector: 'US Mega-Cap Blue Chips',
    current_price: 40659.70,
    day_change: 188.90,
    day_change_pct: 0.47,
    volume_24h: '380M',
    market_cap: '$14.2T',
    pe_ratio: 21.4,
    high_52w: 41376.00,
    low_52w: 32417.59,
    beta: 0.88,
    eps: 1900.00,
    description: 'The Dow Jones Industrial Average is a price-weighted measure of 30 U.S. blue-chip companies across all industries excluding transportation and utilities.',
    ai_summary: 'Historic blue-chip industrial benchmark reflecting traditional corporate earnings health.',
    ai_sentiment: 'Bullish',
    color: '#002B49',
  },
  {
    ticker: 'RUT',
    name: 'Russell 2000 Index',
    type: 'Index',
    category: 'indices',
    region: 'US',
    country: 'United States',
    exchange: 'INDEX',
    currency: 'USD',
    sector: 'US Small-Cap',
    current_price: 2148.50,
    day_change: 28.40,
    day_change_pct: 1.34,
    volume_24h: '920M',
    market_cap: '$3.2T',
    pe_ratio: 22.8,
    high_52w: 2299.16,
    low_52w: 1633.67,
    beta: 1.25,
    eps: 94.23,
    description: 'The Russell 2000 Index measures the performance of the small-cap segment of the US equity universe.',
    ai_summary: 'Leading measure of domestic US small-business and mid-market growth prospects.',
    ai_sentiment: 'Bullish',
    color: '#000000',
  },
  {
    ticker: 'VIX',
    name: 'CBOE Volatility Index',
    type: 'Index',
    category: 'indices',
    region: 'US',
    country: 'United States',
    exchange: 'INDEX',
    currency: 'USD',
    sector: 'Volatility',
    current_price: 15.24,
    day_change: -0.85,
    day_change_pct: -5.28,
    volume_24h: '85M',
    market_cap: 'N/A',
    pe_ratio: null,
    high_52w: 65.73,
    low_52w: 11.52,
    beta: -3.80,
    eps: null,
    description: 'The CBOE Volatility Index (VIX) is a real-time market index representing the market’s expectations for the relative strength of near-term price changes of the S&P 500.',
    ai_summary: 'Wall Street’s primary fear gauge; low values indicate stable bullish equity regimes.',
    ai_sentiment: 'Neutral',
    color: '#800080',
  },

  // =========================================================================
  // 14. KAZAKHSTAN MARKET LEADERS (Real Publicly Traded Companies)
  // =========================================================================
  {
    ticker: 'KSPI',
    name: 'Kaspi.kz JSC',
    type: 'Stock',
    category: 'stocks',
    region: 'Emerging Markets',
    country: 'Kazakhstan',
    exchange: 'NASDAQ',
    currency: 'USD',
    sector: 'Financial Technology',
    industry: 'Consumer Finance & Payments',
    current_price: 99.10,
    day_change: 0.40,
    day_change_pct: 0.41,
    volume_24h: '450K',
    market_cap: '$19.2B',
    pe_ratio: 10.8,
    high_52w: 140.00,
    low_52w: 88.50,
    beta: 0.95,
    eps: 9.15,
    description: 'JSC Kaspi.kz operates the leading two-sided Super App fintech ecosystem in Kazakhstan, encompassing Payments, Marketplace, and Consumer & SME Fintech Services.',
    ai_summary: 'Exceptional profitability, 70%+ net margins, and dominant digital ecosystem in Central Asia with rapid cross-border expansion.',
    ai_sentiment: 'Bullish',
    color: '#F14635',
  },
  {
    ticker: 'KAP',
    name: 'NAC Kazatomprom JSC',
    type: 'Stock',
    category: 'stocks',
    region: 'Emerging Markets',
    country: 'Kazakhstan',
    exchange: 'LSE',
    currency: 'USD',
    sector: 'Energy & Materials',
    industry: 'Uranium Mining & Nuclear Fuel',
    current_price: 38.50,
    day_change: 0.85,
    day_change_pct: 2.26,
    volume_24h: '320K',
    market_cap: '$10.2B',
    pe_ratio: 14.2,
    high_52w: 48.00,
    low_52w: 28.50,
    beta: 0.82,
    eps: 2.71,
    description: 'National Atomic Company Kazatomprom JSC is the world’s largest producer of natural uranium, accounting for over 20% of global primary uranium production.',
    ai_summary: 'Strategic supplier to global nuclear energy resurgence; world-class lowest-cost In-Situ Recovery (ISR) mining assets and strong dividend yields.',
    ai_sentiment: 'Bullish',
    color: '#005596',
  },
  {
    ticker: 'HSBK',
    name: 'Halyk Savings Bank of Kazakhstan',
    type: 'Stock',
    category: 'stocks',
    region: 'Emerging Markets',
    country: 'Kazakhstan',
    exchange: 'LSE',
    currency: 'USD',
    sector: 'Financials',
    industry: 'Commercial & Retail Banking',
    current_price: 19.80,
    day_change: 0.25,
    day_change_pct: 1.28,
    volume_24h: '280K',
    market_cap: '$4.35B',
    pe_ratio: 4.8,
    high_52w: 22.40,
    low_52w: 13.60,
    beta: 0.78,
    eps: 4.12,
    description: 'Halyk Bank is the largest universal commercial banking group in Kazakhstan and Central Asia, providing corporate, SME, retail banking, and digital financial services.',
    ai_summary: 'Industry-leading ROE of 30%+, robust loan portfolio quality, high dividend payout history, and solid capital adequacy ratios.',
    ai_sentiment: 'Bullish',
    color: '#00843D',
  },
  {
    ticker: 'KMGZ',
    name: 'JSC NC KazMunayGas',
    type: 'Stock',
    category: 'stocks',
    region: 'Emerging Markets',
    country: 'Kazakhstan',
    exchange: 'AIX',
    currency: 'USD',
    sector: 'Energy',
    industry: 'Oil & Gas Exploration & Refining',
    current_price: 27.60,
    day_change: 0.45,
    day_change_pct: 1.66,
    volume_24h: '190K',
    market_cap: '$16.85B',
    pe_ratio: 6.5,
    high_52w: 32.00,
    low_52w: 21.50,
    beta: 0.88,
    eps: 4.25,
    description: 'JSC NC KazMunayGas is the national operator of the oil and gas industry of Kazakhstan, managing major assets in exploration, production, refining, and pipeline transport across the Caspian basin.',
    ai_summary: 'Direct exposure to massive Tengiz, Kashagan, and Karachaganak fields; strategic sovereign energy assets with high cash generation.',
    ai_sentiment: 'Bullish',
    color: '#0047BA',
  },
  {
    ticker: 'KEGC',
    name: 'KEGOC JSC',
    type: 'Stock',
    category: 'stocks',
    region: 'Emerging Markets',
    country: 'Kazakhstan',
    exchange: 'KASE',
    currency: 'USD',
    sector: 'Utilities',
    industry: 'Electric Power Transmission Grid',
    current_price: 3.25,
    day_change: 0.04,
    day_change_pct: 1.25,
    volume_24h: '85K',
    market_cap: '$1.08B',
    pe_ratio: 8.2,
    high_52w: 3.85,
    low_52w: 2.80,
    beta: 0.45,
    eps: 0.40,
    description: 'Kazakhstan Electricity Grid Operating Company (KEGOC) operates the National Power Grid of Kazakhstan, managing high-voltage transmission and interstate energy flows.',
    ai_summary: 'Regulated utility monopoly with stable tariff structures, sovereign backing, and consistent semi-annual dividend payouts.',
    ai_sentiment: 'Neutral',
    color: '#006699',
  },
  {
    ticker: 'AIRA',
    name: 'Air Astana JSC',
    type: 'Stock',
    category: 'stocks',
    region: 'Emerging Markets',
    country: 'Kazakhstan',
    exchange: 'LSE',
    currency: 'USD',
    sector: 'Industrials',
    industry: 'Airlines & Aviation Services',
    current_price: 7.80,
    day_change: 0.12,
    day_change_pct: 1.56,
    volume_24h: '110K',
    market_cap: '$840M',
    pe_ratio: 7.4,
    high_52w: 10.50,
    low_52w: 6.80,
    beta: 0.90,
    eps: 1.05,
    description: 'Air Astana is the flag carrier airline group of Kazakhstan, operating full-service Air Astana and low-cost carrier FlyArystan across Central Asia, Europe, and Asia-Pacific.',
    ai_summary: 'Dominant regional aviation hub with modern fuel-efficient fleet and high post-IPO route expansion between Europe and Asia.',
    ai_sentiment: 'Bullish',
    color: '#D4AF37',
  },
  {
    ticker: 'KZTK',
    name: 'Kazakhtelecom JSC',
    type: 'Stock',
    category: 'stocks',
    region: 'Emerging Markets',
    country: 'Kazakhstan',
    exchange: 'KASE',
    currency: 'USD',
    sector: 'Telecommunications',
    industry: 'Broadband, Mobile & Cloud Infrastructure',
    current_price: 76.00,
    day_change: 1.20,
    day_change_pct: 1.60,
    volume_24h: '45K',
    market_cap: '$820M',
    pe_ratio: 5.6,
    high_52w: 88.00,
    low_52w: 62.00,
    beta: 0.65,
    eps: 13.50,
    description: 'Kazakhtelecom JSC is the largest telecommunications operator in Kazakhstan, owning national fiber-optic backbone, 5G spectrum, and enterprise cloud data centers.',
    ai_summary: 'Dominant broadband market share of 70%+, expanding 5G rollout, and cash generation supporting dividend yield.',
    ai_sentiment: 'Bullish',
    color: '#002B49',
  },
  {
    ticker: 'CCBN',
    name: 'Bank CenterCredit JSC',
    type: 'Stock',
    category: 'stocks',
    region: 'Emerging Markets',
    country: 'Kazakhstan',
    exchange: 'KASE',
    currency: 'USD',
    sector: 'Financials',
    industry: 'Commercial & Digital Banking',
    current_price: 4.12,
    day_change: 0.08,
    day_change_pct: 1.98,
    volume_24h: '150K',
    market_cap: '$1.48B',
    pe_ratio: 3.9,
    high_52w: 4.90,
    low_52w: 2.70,
    beta: 0.85,
    eps: 1.05,
    description: 'Bank CenterCredit (BCC) is one of the oldest and largest commercial banks in Kazakhstan, providing modern digital retail banking, SME lending, and wealth management.',
    ai_summary: 'Rapid retail user growth, successful integration of Eco Center Bank assets, and low valuation multiples.',
    ai_sentiment: 'Bullish',
    color: '#107C41',
  },

  // =========================================================================
  // 15. GLOBAL OIL & ENERGY GIANTS
  // =========================================================================
  {
    ticker: 'XOM',
    name: 'Exxon Mobil Corporation',
    type: 'Stock',
    category: 'stocks',
    region: 'US',
    country: 'United States',
    exchange: 'NYSE',
    currency: 'USD',
    sector: 'Energy',
    industry: 'Integrated Oil & Gas',
    current_price: 158.99,
    day_change: -0.08,
    day_change_pct: -0.05,
    volume_24h: '18.4M',
    market_cap: '$632.4B',
    pe_ratio: 14.5,
    high_52w: 165.20,
    low_52w: 98.60,
    beta: 0.95,
    eps: 10.96,
    description: 'Exxon Mobil Corporation explores for and produces crude oil and natural gas in the United States and internationally, with world-scale operations in Guyana and Permian Basin.',
    ai_summary: 'Industry benchmark for low-cost upstream expansion, strong free cash flow yield, and pioneer in carbon capture and storage.',
    ai_sentiment: 'Bullish',
    color: '#FF0000',
  },
  {
    ticker: 'CVX',
    name: 'Chevron Corporation',
    type: 'Stock',
    category: 'stocks',
    region: 'US',
    country: 'United States',
    exchange: 'NYSE',
    currency: 'USD',
    sector: 'Energy',
    industry: 'Integrated Oil & Gas',
    current_price: 199.94,
    day_change: -0.06,
    day_change_pct: -0.03,
    volume_24h: '12.8M',
    market_cap: '$368.5B',
    pe_ratio: 15.2,
    high_52w: 208.40,
    low_52w: 139.50,
    beta: 1.08,
    eps: 13.15,
    description: 'Chevron Corporation engages in integrated energy and chemical operations worldwide, holding major assets in the Permian Basin, Gulf of Mexico, Kazakhstan (TCO), and LNG projects.',
    ai_summary: 'Robust balance sheet, multi-decade dividend growth track record, and prime positioning in low-break-even shale and offshore basins.',
    ai_sentiment: 'Bullish',
    color: '#0054A6',
  },
  {
    ticker: 'COP',
    name: 'ConocoPhillips',
    type: 'Stock',
    category: 'stocks',
    region: 'US',
    country: 'United States',
    exchange: 'NYSE',
    currency: 'USD',
    sector: 'Energy',
    industry: 'Oil & Gas Exploration & Production',
    current_price: 125.91,
    day_change: -0.03,
    day_change_pct: -0.02,
    volume_24h: '8.6M',
    market_cap: '$148.2B',
    pe_ratio: 13.8,
    high_52w: 138.50,
    low_52w: 97.40,
    beta: 1.18,
    eps: 9.12,
    description: 'ConocoPhillips explores for, produces, transports, and markets crude oil, bitumen, natural gas, and LNG across North America, Europe, Asia, and Australia.',
    ai_summary: 'Pure-play E&P powerhouse with sector-leading capital returns, Marathon Oil acquisition synergies, and premium Permian acreage.',
    ai_sentiment: 'Bullish',
    color: '#D52B1E',
  },
  {
    ticker: 'SHEL',
    name: 'Shell PLC',
    type: 'Stock',
    category: 'stocks',
    region: 'Europe',
    country: 'United Kingdom',
    exchange: 'NYSE',
    currency: 'USD',
    sector: 'Energy',
    industry: 'Integrated Oil & Gas & LNG',
    current_price: 90.21,
    day_change: -0.26,
    day_change_pct: -0.29,
    volume_24h: '9.2M',
    market_cap: '$228.6B',
    pe_ratio: 11.4,
    high_52w: 96.80,
    low_52w: 63.20,
    beta: 0.72,
    eps: 7.91,
    description: 'Shell plc operates as an energy and petrochemical company worldwide, maintaining global market leadership in Liquefied Natural Gas (LNG) trading and marketing.',
    ai_summary: 'World-leading global LNG portfolio, substantial share buyback programs, and disciplined capital allocation under simplified corporate structure.',
    ai_sentiment: 'Bullish',
    color: '#FFD500',
  },
  {
    ticker: 'BP',
    name: 'BP p.l.c.',
    type: 'Stock',
    category: 'stocks',
    region: 'Europe',
    country: 'United Kingdom',
    exchange: 'NYSE',
    currency: 'USD',
    sector: 'Energy',
    industry: 'Integrated Oil & Gas',
    current_price: 42.26,
    day_change: -0.27,
    day_change_pct: -0.63,
    volume_24h: '11.5M',
    market_cap: '$96.4B',
    pe_ratio: 10.2,
    high_52w: 48.90,
    low_52w: 31.80,
    beta: 0.75,
    eps: 4.14,
    description: 'BP p.l.c. delivers energy products and services worldwide, operating upstream hydrocarbon development alongside global fuels, lubricants, and convenience retail networks.',
    ai_summary: 'Attractive dividend yield, deep value valuation multiples, and strong offshore Gulf of Mexico and North Sea production assets.',
    ai_sentiment: 'Neutral',
    color: '#007A3D',
  },
  {
    ticker: 'TTE',
    name: 'TotalEnergies SE',
    type: 'Stock',
    category: 'stocks',
    region: 'Europe',
    country: 'France',
    exchange: 'NYSE',
    currency: 'USD',
    sector: 'Energy',
    industry: 'Integrated Oil, Gas & Multi-Energy',
    current_price: 88.14,
    day_change: -0.19,
    day_change_pct: -0.22,
    volume_24h: '4.8M',
    market_cap: '$162.8B',
    pe_ratio: 9.8,
    high_52w: 94.50,
    low_52w: 62.10,
    beta: 0.74,
    eps: 8.99,
    description: 'TotalEnergies SE is a global multi-energy company that produces and markets fuels, natural gas, electricity, and renewables across more than 130 countries.',
    ai_summary: 'Lowest production cost among European majors, highly diversified global LNG footprint, and rapid profitable integrated power expansion.',
    ai_sentiment: 'Bullish',
    color: '#ED1B24',
  },
  {
    ticker: 'OXY',
    name: 'Occidental Petroleum Corporation',
    type: 'Stock',
    category: 'stocks',
    region: 'US',
    country: 'United States',
    exchange: 'NYSE',
    currency: 'USD',
    sector: 'Energy',
    industry: 'Oil & Gas Exploration & Chemicals',
    current_price: 58.35,
    day_change: -0.01,
    day_change_pct: -0.02,
    volume_24h: '14.2M',
    market_cap: '$54.8B',
    pe_ratio: 14.8,
    high_52w: 71.20,
    low_52w: 48.60,
    beta: 1.55,
    eps: 3.94,
    description: 'Occidental Petroleum Corporation acquires, explores, and develops oil and gas properties, with dominant acreage in the Permian Basin and OxyChem chemical manufacturing.',
    ai_summary: 'Major backing from Berkshire Hathaway; CrownRock integration boosts Permian scale alongside commercial Direct Air Capture (DAC) leadership.',
    ai_sentiment: 'Bullish',
    color: '#002F6C',
  },
  {
    ticker: 'EOG',
    name: 'EOG Resources, Inc.',
    type: 'Stock',
    category: 'stocks',
    region: 'US',
    country: 'United States',
    exchange: 'NYSE',
    currency: 'USD',
    sector: 'Energy',
    industry: 'Oil & Gas Exploration & Production',
    current_price: 144.55,
    day_change: 1.94,
    day_change_pct: 1.36,
    volume_24h: '5.2M',
    market_cap: '$81.4B',
    pe_ratio: 12.6,
    high_52w: 154.20,
    low_52w: 112.50,
    beta: 1.25,
    eps: 11.47,
    description: 'EOG Resources, Inc. is an American energy company engaged in hydrocarbon exploration in the Delaware Basin, Eagle Ford, Bakken, and Dorado natural gas plays.',
    ai_summary: 'Pioneer of organic exploration, zero long-term net debt, and pristine premium well returns driving high ROCE.',
    ai_sentiment: 'Bullish',
    color: '#1B365D',
  },
  {
    ticker: 'SLB',
    name: 'SLB (Schlumberger Limited)',
    type: 'Stock',
    category: 'stocks',
    region: 'US',
    country: 'United States',
    exchange: 'NYSE',
    currency: 'USD',
    sector: 'Energy',
    industry: 'Oilfield Services & Technology',
    current_price: 53.37,
    day_change: -0.40,
    day_change_pct: -0.75,
    volume_24h: '12.1M',
    market_cap: '$74.6B',
    pe_ratio: 16.2,
    high_52w: 62.10,
    low_52w: 39.80,
    beta: 1.42,
    eps: 3.29,
    description: 'SLB is the world’s leading technology provider for the energy industry, delivering reservoir characterization, drilling, production, and digital AI energy software.',
    ai_summary: 'International and offshore drilling upcycle beneficiary; ChampionX acquisition strengthens high-margin production chemicals and artificial lift.',
    ai_sentiment: 'Bullish',
    color: '#001489',
  },
  {
    ticker: 'CNQ',
    name: 'Canadian Natural Resources',
    type: 'Stock',
    category: 'stocks',
    region: 'Canada',
    country: 'Canada',
    exchange: 'NYSE',
    currency: 'USD',
    sector: 'Energy',
    industry: 'Oil Sands & Heavy Crude Production',
    current_price: 48.32,
    day_change: 0.35,
    day_change_pct: 0.73,
    volume_24h: '7.8M',
    market_cap: '$101.5B',
    pe_ratio: 13.1,
    high_52w: 56.40,
    low_52w: 36.20,
    beta: 1.35,
    eps: 3.69,
    description: 'Canadian Natural Resources Limited is a senior oil and natural gas production company with premier oil sands mining, thermal in situ, and conventional assets in Western Canada.',
    ai_summary: 'Multi-decade zero-decline oil sands reserves, ultra-low break-evens ($35/bbl WTI), and 100% free cash flow returned to shareholders via dividends and buybacks.',
    ai_sentiment: 'Bullish',
    color: '#C41230',
  },
  {
    ticker: 'EQNR',
    name: 'Equinor ASA',
    type: 'Stock',
    category: 'stocks',
    region: 'Europe',
    country: 'Norway',
    exchange: 'NYSE',
    currency: 'USD',
    sector: 'Energy',
    industry: 'Integrated Oil, Gas & Offshore Wind',
    current_price: 41.25,
    day_change: 0.48,
    day_change_pct: 1.18,
    volume_24h: '3.6M',
    market_cap: '$84.2B',
    pe_ratio: 8.5,
    high_52w: 46.80,
    low_52w: 26.50,
    beta: 0.78,
    eps: 4.85,
    description: 'Equinor ASA operates as an energy company on the Norwegian Continental Shelf and internationally, supplying natural gas and offshore hydrocarbons to European markets.',
    ai_summary: 'Crucial European energy security provider, high-margin Johan Sverdrup field production, and solid sovereign cash generation.',
    ai_sentiment: 'Bullish',
    color: '#FF1243',
  },
  {
    ticker: 'FANG',
    name: 'Diamondback Energy, Inc.',
    type: 'Stock',
    category: 'stocks',
    region: 'US',
    country: 'United States',
    exchange: 'NASDAQ',
    currency: 'USD',
    sector: 'Energy',
    industry: 'Oil & Gas Exploration & Production',
    current_price: 203.70,
    day_change: 1.23,
    day_change_pct: 0.61,
    volume_24h: '2.8M',
    market_cap: '$37.8B',
    pe_ratio: 11.2,
    high_52w: 218.50,
    low_52w: 142.00,
    beta: 1.45,
    eps: 18.19,
    description: 'Diamondback Energy, Inc. is an independent oil and natural gas company focused on the acquisition, development, exploration, and exploitation of unconventional onshore oil reserves in the Permian Basin.',
    ai_summary: 'Endeavor Energy merger creates tier-one Permian pure play with top-decile capital efficiency and aggressive shareholder return framework.',
    ai_sentiment: 'Bullish',
    color: '#002B49',
  },
  {
    ticker: 'MPC',
    name: 'Marathon Petroleum Corporation',
    type: 'Stock',
    category: 'stocks',
    region: 'US',
    country: 'United States',
    exchange: 'NYSE',
    currency: 'USD',
    sector: 'Energy',
    industry: 'Oil Refining & Marketing',
    current_price: 354.92,
    day_change: -0.50,
    day_change_pct: -0.14,
    volume_24h: '3.1M',
    market_cap: '$58.2B',
    pe_ratio: 10.6,
    high_52w: 375.00,
    low_52w: 135.00,
    beta: 1.28,
    eps: 33.48,
    description: 'Marathon Petroleum Corporation operates the largest refining system in the United States, along with midstream pipeline networks via MPLX LP.',
    ai_summary: 'Premier US refining scale, high crack spread conversion, and massive cumulative share repurchases.',
    ai_sentiment: 'Bullish',
    color: '#003865',
  },
  {
    ticker: 'VLO',
    name: 'Valero Energy Corporation',
    type: 'Stock',
    category: 'stocks',
    region: 'US',
    country: 'United States',
    exchange: 'NYSE',
    currency: 'USD',
    sector: 'Energy',
    industry: 'Oil Refining & Renewable Diesel',
    current_price: 342.78,
    day_change: 1.11,
    day_change_pct: 0.32,
    volume_24h: '4.2M',
    market_cap: '$47.5B',
    pe_ratio: 11.2,
    high_52w: 360.00,
    low_52w: 120.00,
    beta: 1.32,
    eps: 30.60,
    description: 'Valero Energy Corporation manufactures and markets transportation fuels and petrochemical products across the US, Canada, and UK, and is the world’s largest producer of renewable diesel.',
    ai_summary: 'Advantaged coastal complex refinery configuration, heavy crude processing flexibility, and high renewable diesel margins.',
    ai_sentiment: 'Bullish',
    color: '#00857C',
  },
  {
    ticker: 'PSX',
    name: 'Phillips 66',
    type: 'Stock',
    category: 'stocks',
    region: 'US',
    country: 'United States',
    exchange: 'NYSE',
    currency: 'USD',
    sector: 'Energy',
    industry: 'Refining, Midstream & Chemicals',
    current_price: 233.48,
    day_change: -0.13,
    day_change_pct: -0.06,
    volume_24h: '3.4M',
    market_cap: '$51.8B',
    pe_ratio: 12.8,
    high_52w: 245.00,
    low_52w: 110.00,
    beta: 1.15,
    eps: 18.24,
    description: 'Phillips 66 operates as an energy manufacturing and logistics company with integrated operations across refining, midstream pipelines, chemicals (CPChem), and marketing.',
    ai_summary: 'Diversified downstream and midstream cash engine; Rodeo Renewable Energy Complex conversion and activist cost reduction target execution.',
    ai_sentiment: 'Bullish',
    color: '#ED1B2D',
  },
  {
    ticker: 'HAL',
    name: 'Halliburton Company',
    type: 'Stock',
    category: 'stocks',
    region: 'US',
    country: 'United States',
    exchange: 'NYSE',
    currency: 'USD',
    sector: 'Energy',
    industry: 'Oilfield Equipment & Services',
    current_price: 34.38,
    day_change: -0.04,
    day_change_pct: -0.12,
    volume_24h: '8.9M',
    market_cap: '$29.8B',
    pe_ratio: 11.5,
    high_52w: 42.50,
    low_52w: 27.80,
    beta: 1.62,
    eps: 2.99,
    description: 'Halliburton Company provides products and services to the energy industry across drilling and evaluation, completion and production, and subsurface well modeling.',
    ai_summary: 'Market leader in North American hydraulic fracturing and electric-powered e-fleet completions, with accelerating international margin expansion.',
    ai_sentiment: 'Neutral',
    color: '#D52B1E',
  },
  {
    ticker: 'BKR',
    name: 'Baker Hughes Company',
    type: 'Stock',
    category: 'stocks',
    region: 'US',
    country: 'United States',
    exchange: 'NASDAQ',
    currency: 'USD',
    sector: 'Energy',
    industry: 'Industrial Energy Technology & Turbomachinery',
    current_price: 64.95,
    day_change: 0.13,
    day_change_pct: 0.20,
    volume_24h: '6.5M',
    market_cap: '$64.2B',
    pe_ratio: 18.4,
    high_52w: 70.20,
    low_52w: 31.40,
    beta: 1.22,
    eps: 3.53,
    description: 'Baker Hughes Company provides energy technology solutions including Gas Technology equipment, LNG liquefaction trains, and oilfield services worldwide.',
    ai_summary: 'Dominant global supplier of mission-critical LNG turbomachinery; booming multi-year orders for global LNG capacity expansions and data center power.',
    ai_sentiment: 'Bullish',
    color: '#005544',
  },
  {
    ticker: 'ENB',
    name: 'Enbridge Inc.',
    type: 'Stock',
    category: 'stocks',
    region: 'Canada',
    country: 'Canada',
    exchange: 'NYSE',
    currency: 'USD',
    sector: 'Energy',
    industry: 'Energy Infrastructure & Pipelines',
    current_price: 43.85,
    day_change: 0.15,
    day_change_pct: 0.34,
    volume_24h: '5.8M',
    market_cap: '$108.4B',
    pe_ratio: 18.2,
    high_52w: 47.50,
    low_52w: 32.10,
    beta: 0.68,
    eps: 2.41,
    description: 'Enbridge Inc. operates the world’s longest crude oil and liquid hydrocarbon transportation system, transporting 30% of the crude oil produced in North America.',
    ai_summary: 'Toll-booth business model with 98% cost-of-service/take-or-pay regulated utility contracts supporting reliable 6.5%+ dividend yields.',
    ai_sentiment: 'Bullish',
    color: '#FDB813',
  },
];

