-- =============================================================================
-- MIGRATION: Cleanup Mock Users & Recalculate Tournament Leaderboards
-- Project: Nexra Platform (Supabase PostgreSQL)
-- Description: Removes all synthetic/mock bot users generated by seeder,
--              cleans up child references (participants, trades, holdings, portfolios),
--              preserves real accounts ('akzeineperkin'), and recalculates rankings.
-- =============================================================================

BEGIN;

-- 1. Create a temporary table of mock user IDs to be purged
CREATE TEMP TABLE temp_mock_user_ids AS
SELECT p.id AS user_id
FROM public.profiles p
WHERE 
  -- Identify mock bot usernames
  p.username IN (
    'SatoshiQuant',
    'ValkyrieTrading',
    'CyberBull_99',
    'AlphaSeeker_X',
    'ApexCapital',
    'DeltaHedger',
    'VectorQuant',
    'NovaTrader'
  )
  -- Filter by mock identifiers or bot IDs
  OR p.id LIKE 'bot-%'
  OR p.id LIKE 'mock-%'
  -- Exclude real users explicitly (such as 'akzeineperkin')
  AND p.username NOT ILIKE '%akzeineperkin%';

-- Also check auth.users if metadata or mock domains are present
INSERT INTO temp_mock_user_ids (user_id)
SELECT u.id
FROM auth.users u
WHERE (
  u.email ILIKE '%@mock.local'
  OR u.email ILIKE '%@antigravity.test'
  OR u.email ILIKE '%@example.com'
  OR (u.raw_user_meta_data->>'is_mock')::boolean IS TRUE
  OR u.raw_user_meta_data->>'username' IN (
    'SatoshiQuant', 'ValkyrieTrading', 'CyberBull_99',
    'AlphaSeeker_X', 'ApexCapital', 'DeltaHedger', 'VectorQuant'
  )
)
AND u.email NOT ILIKE '%akzeineperkin%'
AND u.id NOT IN (SELECT user_id FROM temp_mock_user_ids);

-- 2. Remove mock entries from tournament/challenge participants
DELETE FROM public.challenge_participants
WHERE user_id IN (SELECT user_id FROM temp_mock_user_ids);

-- If table tournament_participants exists in legacy schema, clean up
DO $$
BEGIN
  IF EXISTS (SELECT FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'tournament_participants') THEN
    DELETE FROM public.tournament_participants WHERE user_id IN (SELECT user_id FROM temp_mock_user_ids);
  END IF;
END $$;

-- 3. Remove mock holdings & transactions linked to mock user portfolios
DELETE FROM public.holdings
WHERE portfolio_id IN (
  SELECT id FROM public.portfolios WHERE user_id IN (SELECT user_id FROM temp_mock_user_ids)
);

DELETE FROM public.transactions
WHERE portfolio_id IN (
  SELECT id FROM public.portfolios WHERE user_id IN (SELECT user_id FROM temp_mock_user_ids)
);

-- If trades table exists in legacy schema, clean up
DO $$
BEGIN
  IF EXISTS (SELECT FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'trades') THEN
    DELETE FROM public.trades WHERE user_id IN (SELECT user_id FROM temp_mock_user_ids);
  END IF;
END $$;

-- 4. Remove mock portfolios
DELETE FROM public.portfolios
WHERE user_id IN (SELECT user_id FROM temp_mock_user_ids);

-- 5. Remove mock watchlists & notifications
DELETE FROM public.watchlists
WHERE user_id IN (SELECT user_id FROM temp_mock_user_ids);

DELETE FROM public.notifications
WHERE user_id IN (SELECT user_id FROM temp_mock_user_ids);

-- 6. Remove mock profiles
DELETE FROM public.profiles
WHERE id IN (SELECT user_id FROM temp_mock_user_ids);

-- 7. Remove mock auth.users (if applicable)
DELETE FROM auth.users
WHERE id IN (SELECT user_id FROM temp_mock_user_ids);

-- 8. Recalculate Leaderboard Standings for All Real Active Tournaments
-- Net Return % = ((current_value - starting_capital) / starting_capital) * 100
WITH ranked_participants AS (
  SELECT 
    cp.id AS participant_id,
    ROW_NUMBER() OVER (
      PARTITION BY cp.challenge_id 
      ORDER BY 
        CASE 
          WHEN cp.starting_capital > 0 THEN ((cp.current_value - cp.starting_capital) / cp.starting_capital) * 100 
          ELSE 0 
        END DESC,
        cp.joined_at ASC
    ) AS new_rank,
    CASE 
      WHEN cp.starting_capital > 0 THEN ((cp.current_value - cp.starting_capital) / cp.starting_capital) * 100 
      ELSE 0 
    END AS calculated_return_pct,
    (cp.current_value - cp.starting_capital) AS calculated_pnl
  FROM public.challenge_participants cp
)
UPDATE public.challenge_participants target
SET 
  rank = rp.new_rank,
  pnl = rp.calculated_pnl
FROM ranked_participants rp
WHERE target.id = rp.participant_id;

-- 9. Clean up temporary table
DROP TABLE temp_mock_user_ids;

COMMIT;
