-- =============================================================================
-- SUPABASE MIGRATION: 20260818_cleanup_mock_users.sql
-- Project: Nexra Platform (Supabase PostgreSQL)
-- Description: Removes all dummy mock users generated by the antigravity factory,
--              cascades through child tables, preserves real user accounts ('akzeineperkin'),
--              and recalculates active tournament standings strictly by Net Return %.
-- =============================================================================

BEGIN;

-- 1. Identify mock user IDs
CREATE TEMP TABLE temp_mock_user_ids AS
SELECT p.id AS user_id
FROM public.profiles p
WHERE 
  p.username IN (
    'SatoshiQuant',
    'ValkyrieTrading',
    'CyberBull_99',
    'AlphaSeeker_X',
    'ApexCapital',
    'DeltaHedger',
    'VectorQuant',
    'NovaTrader'
  )
  OR p.id LIKE 'bot-%'
  OR p.id LIKE 'mock-%'
  AND p.username NOT ILIKE '%akzeineperkin%';

INSERT INTO temp_mock_user_ids (user_id)
SELECT u.id
FROM auth.users u
WHERE (
  u.email ILIKE '%@mock.local'
  OR u.email ILIKE '%@antigravity.test'
  OR u.email ILIKE '%@example.com'
  OR (u.raw_user_meta_data->>'is_mock')::boolean IS TRUE
  OR u.raw_user_meta_data->>'username' IN (
    'SatoshiQuant', 'ValkyrieTrading', 'CyberBull_99',
    'AlphaSeeker_X', 'ApexCapital', 'DeltaHedger', 'VectorQuant'
  )
)
AND u.email NOT ILIKE '%akzeineperkin%'
AND u.id NOT IN (SELECT user_id FROM temp_mock_user_ids);

-- 2. Remove from challenge/tournament participants
DELETE FROM public.challenge_participants
WHERE user_id IN (SELECT user_id FROM temp_mock_user_ids);

DO $$
BEGIN
  IF EXISTS (SELECT FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'tournament_participants') THEN
    DELETE FROM public.tournament_participants WHERE user_id IN (SELECT user_id FROM temp_mock_user_ids);
  END IF;
END $$;

-- 3. Remove from holdings and transactions
DELETE FROM public.holdings
WHERE portfolio_id IN (
  SELECT id FROM public.portfolios WHERE user_id IN (SELECT user_id FROM temp_mock_user_ids)
);

DELETE FROM public.transactions
WHERE portfolio_id IN (
  SELECT id FROM public.portfolios WHERE user_id IN (SELECT user_id FROM temp_mock_user_ids)
);

DO $$
BEGIN
  IF EXISTS (SELECT FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'trades') THEN
    DELETE FROM public.trades WHERE user_id IN (SELECT user_id FROM temp_mock_user_ids);
  END IF;
END $$;

-- 4. Remove portfolios
DELETE FROM public.portfolios
WHERE user_id IN (SELECT user_id FROM temp_mock_user_ids);

-- 5. Remove watchlists & notifications
DELETE FROM public.watchlists
WHERE user_id IN (SELECT user_id FROM temp_mock_user_ids);

DELETE FROM public.notifications
WHERE user_id IN (SELECT user_id FROM temp_mock_user_ids);

-- 6. Remove profiles
DELETE FROM public.profiles
WHERE id IN (SELECT user_id FROM temp_mock_user_ids);

-- 7. Remove auth.users
DELETE FROM auth.users
WHERE id IN (SELECT user_id FROM temp_mock_user_ids);

-- 8. Recalculate standings for remaining real users based on Net Return %
WITH ranked_participants AS (
  SELECT 
    cp.id AS participant_id,
    ROW_NUMBER() OVER (
      PARTITION BY cp.challenge_id 
      ORDER BY 
        CASE 
          WHEN cp.starting_capital > 0 THEN ((cp.current_value - cp.starting_capital) / cp.starting_capital) * 100 
          ELSE 0 
        END DESC,
        cp.joined_at ASC
    ) AS new_rank,
    (cp.current_value - cp.starting_capital) AS calculated_pnl
  FROM public.challenge_participants cp
)
UPDATE public.challenge_participants target
SET 
  rank = rp.new_rank,
  pnl = rp.calculated_pnl
FROM ranked_participants rp
WHERE target.id = rp.participant_id;

DROP TABLE temp_mock_user_ids;

COMMIT;
